-- ============================================================
-- Bolão Copa 2026 — Full player list from API-Football
-- ============================================================
-- Generated: 2026-05-25T19:46:05.947Z
-- Run this in Supabase SQL Editor

-- Clear existing players
TRUNCATE public.players RESTART IDENTITY CASCADE;

-- Insert all players
INSERT INTO public.players (full_name, team, position, shirt_number) VALUES
  ('T. Courtois', 'Belgium', 'GOL', 1),
  ('S. Lammens', 'Belgium', 'GOL', 1),
  ('M. Penders', 'Belgium', 'GOL', 1),
  ('T. Castagne', 'Belgium', 'DEF', 21),
  ('M. De Cuyper', 'Belgium', 'DEF', 5),
  ('K. De Winter', 'Belgium', 'DEF', 16),
  ('Z. Debast', 'Belgium', 'DEF', 2),
  ('B. Mechele', 'Belgium', 'DEF', 4),
  ('T. Meunier', 'Belgium', 'DEF', 15),
  ('N. Ngoy', 'Belgium', 'DEF', 17),
  ('J. Seys', 'Belgium', 'DEF', 2),
  ('A. Theate', 'Belgium', 'DEF', 3),
  ('K. De Bruyne', 'Belgium', 'MEI', 7),
  ('C. De Ketelaere', 'Belgium', 'MEI', 17),
  ('Diego Moreira', 'Belgium', 'MEI', 7),
  ('A. Onana', 'Belgium', 'MEI', 18),
  ('N. Raskin', 'Belgium', 'MEI', 23),
  ('A. Saelemaekers', 'Belgium', 'MEI', 22),
  ('Y. Tielemans', 'Belgium', 'MEI', 8),
  ('A. Witsel', 'Belgium', 'MEI', 6),
  ('J. Doku', 'Belgium', 'ATA', 11),
  ('M. Fernandez-Pardo', 'Belgium', 'ATA', 7),
  ('R. Lukaku', 'Belgium', 'ATA', 10),
  ('D. Lukebakio', 'Belgium', 'ATA', 14),
  ('M. Maignan', 'France', 'GOL', 16),
  ('R. Risser', 'France', 'GOL', 16),
  ('B. Samba', 'France', 'GOL', 1),
  ('L. Digne', 'France', 'DEF', 3),
  ('M. Gusto', 'France', 'DEF', 2),
  ('L. Hernández', 'France', 'DEF', 21),
  ('T. Hernández', 'France', 'DEF', 22),
  ('I. Konaté', 'France', 'DEF', 15),
  ('M. Lacroix', 'France', 'DEF', 19),
  ('D. Upamecano', 'France', 'DEF', 4),
  ('R. Cherki', 'France', 'MEI', 14),
  ('N. Kanté', 'France', 'MEI', 13),
  ('M. Koné', 'France', 'MEI', 8),
  ('M. Olise', 'France', 'MEI', 11),
  ('A. Rabiot', 'France', 'MEI', 14),
  ('A. Tchouaméni', 'France', 'MEI', 8),
  ('W. Zaïre-Emery', 'France', 'MEI', 18),
  ('M. Akliouche', 'France', 'ATA', 12),
  ('O. Dembélé', 'France', 'ATA', 7),
  ('D. Doué', 'France', 'ATA', 12),
  ('Kylian Mbappé', 'France', 'ATA', 10),
  ('M. Thuram', 'France', 'ATA', 9),
  ('D. Kotarski', 'Croatia', 'GOL', 12),
  ('D. Livaković', 'Croatia', 'GOL', 1),
  ('I. Pandur', 'Croatia', 'GOL', 12),
  ('D. Ćaleta-Car', 'Croatia', 'DEF', 5),
  ('M. Erlić', 'Croatia', 'DEF', 22),
  ('J. Gvardiol', 'Croatia', 'DEF', 4),
  ('M. Pongračić', 'Croatia', 'DEF', 3),
  ('J. Stanišić', 'Croatia', 'DEF', 2),
  ('J. Šutalo', 'Croatia', 'DEF', 6),
  ('L. Vušković', 'Croatia', 'DEF', 4),
  ('M. Baturina', 'Croatia', 'MEI', 16),
  ('T. Fruk', 'Croatia', 'MEI', 19),
  ('K. Jakić', 'Croatia', 'MEI', 18),
  ('M. Kovačić', 'Croatia', 'MEI', 8),
  ('L. Modrić', 'Croatia', 'MEI', 10),
  ('N. Moro', 'Croatia', 'MEI', 8),
  ('M. Pašalić', 'Croatia', 'MEI', 15),
  ('L. Sučić', 'Croatia', 'MEI', 21),
  ('P. Sučić', 'Croatia', 'MEI', 17),
  ('N. Vlašić', 'Croatia', 'MEI', 13),
  ('A. Budimir', 'Croatia', 'ATA', 11),
  ('A. Kramarić', 'Croatia', 'ATA', 9),
  ('I. Matanović', 'Croatia', 'ATA', 21),
  ('P. Musa', 'Croatia', 'ATA', 11),
  ('I. Perišić', 'Croatia', 'ATA', 14),
  ('K. Nordfeldt', 'Sweden', 'GOL', 23),
  ('H. Ekdal', 'Sweden', 'DEF', 2),
  ('G. Gudmundsson', 'Sweden', 'DEF', 5),
  ('I. Hien', 'Sweden', 'DEF', 4),
  ('G. Lagerbielke', 'Sweden', 'DEF', 2),
  ('V. Lindelöf', 'Sweden', 'DEF', 3),
  ('C. Starfelt', 'Sweden', 'DEF', 15),
  ('Y. Ayari', 'Sweden', 'MEI', 18),
  ('L. Bergvall', 'Sweden', 'MEI', 7),
  ('J. Karlström', 'Sweden', 'MEI', 16),
  ('K. Sema', 'Sweden', 'MEI', 13),
  ('E. Smith', 'Sweden', 'MEI', 13),
  ('E. Stroud', 'Sweden', 'MEI', 13),
  ('M. Svanberg', 'Sweden', 'MEI', 19),
  ('D. Svensson', 'Sweden', 'MEI', 8),
  ('B. Zeneli', 'Sweden', 'MEI', 22),
  ('T. Ali', 'Sweden', 'ATA', 21),
  ('A. Elanga', 'Sweden', 'ATA', 11),
  ('V. Gyökeres', 'Sweden', 'ATA', 17),
  ('G. Nilsson', 'Sweden', 'ATA', 9),
  ('B. Nygren', 'Sweden', 'ATA', 10),
  ('Alisson Becker', 'Brazil', 'GOL', 1),
  ('Ederson', 'Brazil', 'GOL', 23),
  ('Weverton', 'Brazil', 'GOL', 1),
  ('Bremer', 'Brazil', 'DEF', 25),
  ('Danilo', 'Brazil', 'DEF', 2),
  ('Gabriel Magalhães', 'Brazil', 'DEF', 3),
  ('Ibañez', 'Brazil', 'DEF', 15),
  ('Léo Pereira', 'Brazil', 'DEF', 15),
  ('Marquinhos', 'Brazil', 'DEF', 4),
  ('Douglas Santos', 'Brazil', 'DEF', 6),
  ('Wesley', 'Brazil', 'DEF', 2),
  ('Casemiro', 'Brazil', 'MEI', 5),
  ('Fabinho', 'Brazil', 'MEI', 15),
  ('Matheus Cunha', 'Brazil', 'ATA', 21),
  ('Endrick', 'Brazil', 'ATA', 19),
  ('Luiz Henrique', 'Brazil', 'ATA', 19),
  ('Gabriel Martinelli', 'Brazil', 'ATA', 22),
  ('Neymar', 'Brazil', 'ATA', 10),
  ('Raphinha', 'Brazil', 'ATA', 10),
  ('Rayan', 'Brazil', 'ATA', 7),
  ('Thiago', 'Brazil', 'ATA', NULL),
  ('Vinícius Júnior', 'Brazil', 'ATA', 10),
  ('K. Martínez', 'Uruguay', 'GOL', 1),
  ('S. Mele', 'Uruguay', 'GOL', 23),
  ('F. Muslera', 'Uruguay', 'GOL', 1),
  ('S. Rochet', 'Uruguay', 'GOL', 1),
  ('R. Araújo', 'Uruguay', 'DEF', 4),
  ('S. Bueno', 'Uruguay', 'DEF', 2),
  ('S. Cáceres', 'Uruguay', 'DEF', 3),
  ('J. Giménez', 'Uruguay', 'DEF', 2),
  ('M. Olivera', 'Uruguay', 'DEF', 16),
  ('J. Piquerez', 'Uruguay', 'DEF', 22),
  ('J. Rodríguez', 'Uruguay', 'DEF', 14),
  ('G. Varela', 'Uruguay', 'DEF', 13),
  ('M. Viña', 'Uruguay', 'DEF', 17),
  ('N. Fonseca', 'Uruguay', 'MEI', 15),
  ('E. Martínez', 'Uruguay', 'MEI', 20),
  ('J. Sanabria', 'Uruguay', 'MEI', 18),
  ('M. Ugarte', 'Uruguay', 'MEI', 5),
  ('F. Valverde', 'Uruguay', 'MEI', 15),
  ('G. de Arrascaeta', 'Uruguay', 'MEI', 10),
  ('N. de la Cruz', 'Uruguay', 'MEI', 7),
  ('R. Aguirre', 'Uruguay', 'ATA', 7),
  ('A. Álvarez', 'Uruguay', 'ATA', 9),
  ('M. Araújo', 'Uruguay', 'ATA', 20),
  ('A. Canobbio', 'Uruguay', 'ATA', 14),
  ('D. Núñez', 'Uruguay', 'ATA', 9),
  ('F. Pellistri', 'Uruguay', 'ATA', 11),
  ('B. Rodríguez', 'Uruguay', 'ATA', 10),
  ('F. Torres', 'Uruguay', 'ATA', 21),
  ('F. Viñas', 'Uruguay', 'ATA', 13),
  ('Á. Montero', 'Colombia', 'GOL', 22),
  ('D. Ospina', 'Colombia', 'GOL', 1),
  ('C. Vargas', 'Colombia', 'GOL', 12),
  ('S. Arias', 'Colombia', 'DEF', 4),
  ('J. Cabal', 'Colombia', 'DEF', 2),
  ('J. Lucumí', 'Colombia', 'DEF', 3),
  ('D. Machado', 'Colombia', 'DEF', 4),
  ('Y. Mina', 'Colombia', 'DEF', 13),
  ('J. Mojica', 'Colombia', 'DEF', 14),
  ('D. Muñoz', 'Colombia', 'DEF', 2),
  ('D. Sánchez', 'Colombia', 'DEF', 23),
  ('K. Castaño', 'Colombia', 'MEI', 5),
  ('J. Lerma', 'Colombia', 'MEI', 16),
  ('Y. Mosquera', 'Colombia', 'MEI', 2),
  ('G. Puerta', 'Colombia', 'MEI', 20),
  ('J. Quintero', 'Colombia', 'MEI', 20),
  ('R. Rios', 'Colombia', 'MEI', 6),
  ('J. Rodríguez', 'Colombia', 'MEI', 10),
  ('J. Arias', 'Colombia', 'ATA', 11),
  ('R. Borré', 'Colombia', 'ATA', 19),
  ('J. Campaz', 'Colombia', 'ATA', 21),
  ('J. Carbonero', 'Colombia', 'ATA', 21),
  ('J. Carrascal', 'Colombia', 'ATA', 8),
  ('J. Córdoba', 'Colombia', 'ATA', 9),
  ('L. Díaz', 'Colombia', 'ATA', 7),
  ('A. Gómez', 'Colombia', 'ATA', 18),
  ('L. Suárez', 'Colombia', 'ATA', 19),
  ('Joan García', 'Spain', 'GOL', 13),
  ('David Raya', 'Spain', 'GOL', 1),
  ('Álex Remiro', 'Spain', 'GOL', 13),
  ('Unai Simón', 'Spain', 'GOL', 23),
  ('Pau Cubarsí Paredes', 'Spain', 'DEF', 15),
  ('Marc Cucurella', 'Spain', 'DEF', 22),
  ('Álex Grimaldo', 'Spain', 'DEF', 3),
  ('D. Huijsen', 'Spain', 'DEF', 5),
  ('Aymeric Laporte', 'Spain', 'DEF', 14),
  ('Marcos Llorente', 'Spain', 'DEF', 5),
  ('Cristhian Mosquera', 'Spain', 'DEF', 3),
  ('Pedro Porro', 'Spain', 'DEF', 12),
  ('Pablo Barrios', 'Spain', 'MEI', 2),
  ('Fermín', 'Spain', 'MEI', 19),
  ('Pablo Fornals', 'Spain', 'MEI', 17),
  ('Dani Olmo', 'Spain', 'MEI', 10),
  ('Pedri', 'Spain', 'MEI', 20),
  ('Rodri', 'Spain', 'MEI', 16),
  ('Carlos Soler', 'Spain', 'MEI', 19),
  ('Martín Zubimendi', 'Spain', 'MEI', 18),
  ('Álex Baena', 'Spain', 'ATA', 16),
  ('Barrenetxea', 'Spain', 'ATA', 11),
  ('Borja Iglesias', 'Spain', 'ATA', 9),
  ('Lamine Yamal', 'Spain', 'ATA', 19),
  ('Víctor Muñoz', 'Spain', 'ATA', NULL),
  ('Mikel Oyarzabal', 'Spain', 'ATA', 21),
  ('Yeremy Pino', 'Spain', 'ATA', 11),
  ('Samu', 'Spain', 'ATA', 3),
  ('Ferran Torres', 'Spain', 'ATA', 7),
  ('D. Henderson', 'England', 'GOL', 13),
  ('J. Pickford', 'England', 'GOL', 1),
  ('A. Ramsdale', 'England', 'GOL', 1),
  ('J. Steele', 'England', 'GOL', 18),
  ('J. Trafford', 'England', 'GOL', 22),
  ('D. Burn', 'England', 'DEF', 12),
  ('M. Guéhi', 'England', 'DEF', 5),
  ('L. Hall', 'England', 'DEF', 3),
  ('E. Konsa', 'England', 'DEF', 2),
  ('T. Livramento', 'England', 'DEF', 16),
  ('H. Maguire', 'England', 'DEF', 6),
  ('D. Spence', 'England', 'DEF', 14),
  ('J. Stones', 'England', 'DEF', 5),
  ('F. Tomori', 'England', 'DEF', 12),
  ('B. White', 'England', 'DEF', 21),
  ('E. Anderson', 'England', 'MEI', 21),
  ('J. Bellingham', 'England', 'MEI', 10),
  ('P. Foden', 'England', 'MEI', 17),
  ('J. Garner', 'England', 'MEI', 14),
  ('J. Henderson', 'England', 'MEI', 8),
  ('K. Mainoo', 'England', 'MEI', 18),
  ('N. O&apos;Reilly', 'England', 'MEI', 18),
  ('C. Palmer', 'England', 'MEI', 20),
  ('M. Rogers', 'England', 'MEI', 15),
  ('A. Wharton', 'England', 'MEI', 16),
  ('H. Barnes', 'England', 'ATA', 17),
  ('J. Bowen', 'England', 'ATA', 20),
  ('D. Calvert-Lewin', 'England', 'ATA', 18),
  ('A. Gordon', 'England', 'ATA', 17),
  ('N. Madueke', 'England', 'ATA', 21),
  ('M. Rashford', 'England', 'ATA', 11),
  ('D. Solanke', 'England', 'ATA', 19),
  ('JD Gunn', 'Panama', 'GOL', 12),
  ('L. Mejía', 'Panama', 'GOL', 1),
  ('O. Mosquera', 'Panama', 'GOL', 22),
  ('E. Roberts', 'Panama', 'GOL', 1),
  ('C. Samudio', 'Panama', 'GOL', 12),
  ('A. Andrade', 'Panama', 'DEF', 16),
  ('C. Blackman', 'Panama', 'DEF', 2),
  ('J. Córdoba', 'Panama', 'DEF', 3),
  ('O. Córdoba', 'Panama', 'DEF', 4),
  ('É. Davis', 'Panama', 'DEF', 15),
  ('O. Davis', 'Panama', 'DEF', 20),
  ('E. Fariña', 'Panama', 'DEF', 5),
  ('K. Galván', 'Panama', 'DEF', 6),
  ('J. Gutiérrez', 'Panama', 'DEF', 23),
  ('J. Hall', 'Panama', 'DEF', 14),
  ('C. Harvey', 'Panama', 'DEF', 14),
  ('M. Krug', 'Panama', 'DEF', 13),
  ('R. Miller', 'Panama', 'DEF', 25),
  ('A. Murillo', 'Panama', 'DEF', 23),
  ('R. Peralta', 'Panama', 'DEF', 5),
  ('J. Ramos', 'Panama', 'DEF', 3),
  ('J. Rivera', 'Panama', 'DEF', NULL),
  ('D. Aparicio', 'Panama', 'MEI', NULL),
  ('Á. Caicedo', 'Panama', 'MEI', NULL),
  ('A. Carrasquilla', 'Panama', 'MEI', 8),
  ('E. Cedeño', 'Panama', 'MEI', 13),
  ('A. Godoy', 'Panama', 'MEI', 20),
  ('A. Knight', 'Panama', 'MEI', 6),
  ('C. Martinez', 'Panama', 'MEI', 6),
  ('R. Phillips', 'Panama', 'MEI', 7),
  ('J. Rodríguez', 'Panama', 'MEI', 7),
  ('M. Sanchez', 'Panama', 'MEI', 8),
  ('J. Welch', 'Panama', 'MEI', 14),
  ('A. Arroyo', 'Panama', 'ATA', 18),
  ('Y. Bárcenas', 'Panama', 'ATA', 11),
  ('K. Barria', 'Panama', 'ATA', NULL),
  ('O. Browne', 'Panama', 'ATA', 21),
  ('I. Díaz', 'Panama', 'ATA', 10),
  ('J. Fajardo', 'Panama', 'ATA', 17),
  ('G. Herbert', 'Panama', 'ATA', 10),
  ('G. Herrera', 'Panama', 'ATA', 9),
  ('H. Hurtado', 'Panama', 'ATA', NULL),
  ('K. Lenis', 'Panama', 'ATA', 13),
  ('J. Murillo', 'Panama', 'ATA', 13),
  ('A. Quintero', 'Panama', 'ATA', 19),
  ('C. Waterman', 'Panama', 'ATA', 18),
  ('C. Yanis', 'Panama', 'ATA', 21),
  ('T. Hayakawa', 'Japan', 'GOL', 12),
  ('K. Osako', 'Japan', 'GOL', 1),
  ('Z. Suzuki', 'Japan', 'GOL', 1),
  ('H. Ito', 'Japan', 'DEF', 21),
  ('Y. Nagatomo', 'Japan', 'DEF', 5),
  ('A. Seko', 'Japan', 'DEF', 22),
  ('Y. Sugawara', 'Japan', 'DEF', 2),
  ('J. Suzuki', 'Japan', 'DEF', 4),
  ('S. Taniguchi', 'Japan', 'DEF', 3),
  ('T. Tomiyasu', 'Japan', 'DEF', 22),
  ('T. Watanabe', 'Japan', 'DEF', 4),
  ('R. Dōan', 'Japan', 'MEI', 10),
  ('D. Kamada', 'Japan', 'MEI', 15),
  ('K. Sano', 'Japan', 'MEI', 5),
  ('S. Tanaka', 'Japan', 'MEI', 8),
  ('K. Goto', 'Japan', 'ATA', NULL),
  ('J. Ito', 'Japan', 'ATA', 14),
  ('D. Maeda', 'Japan', 'ATA', 11),
  ('Keito Nakamura', 'Japan', 'ATA', 13),
  ('Koki Ogawa', 'Japan', 'ATA', 19),
  ('K. Shiogai', 'Japan', 'ATA', 14),
  ('Y. Suzuki', 'Japan', 'ATA', 8),
  ('A. Ueda', 'Japan', 'ATA', 9),
  ('M. Diaw', 'Senegal', 'GOL', 23),
  ('Y. Diouf', 'Senegal', 'GOL', 1),
  ('É. Mendy', 'Senegal', 'GOL', 16),
  ('E. Diouf', 'Senegal', 'DEF', 25),
  ('I. Jakobs', 'Senegal', 'DEF', 14),
  ('K. Koulibaly', 'Senegal', 'DEF', 3),
  ('A. Mendy', 'Senegal', 'DEF', 24),
  ('N. Mendy', 'Senegal', 'DEF', NULL),
  ('M. Niakhaté', 'Senegal', 'DEF', 19),
  ('M. Sarr', 'Senegal', 'DEF', 2),
  ('A. Seck', 'Senegal', 'DEF', 4),
  ('I. Camara', 'Senegal', 'MEI', 14),
  ('L. Camara', 'Senegal', 'MEI', 8),
  ('M. Camara', 'Senegal', 'MEI', 28),
  ('P. Ciss', 'Senegal', 'MEI', 6),
  ('H. Diarra', 'Senegal', 'MEI', 7),
  ('K. Diatta', 'Senegal', 'MEI', 15),
  ('I. Gueye', 'Senegal', 'MEI', 5),
  ('P. Gueye', 'Senegal', 'MEI', 26),
  ('P. Sarr', 'Senegal', 'MEI', 17),
  ('B. Dia', 'Senegal', 'ATA', 9),
  ('M. Diakhon', 'Senegal', 'ATA', 20),
  ('H. Diallo', 'Senegal', 'ATA', 20),
  ('Assane Diao', 'Senegal', 'ATA', 7),
  ('B. Dieng', 'Senegal', 'ATA', 9),
  ('N. Jackson', 'Senegal', 'ATA', 11),
  ('S. Mané', 'Senegal', 'ATA', 10),
  ('I. Mbaye', 'Senegal', 'ATA', 27),
  ('C. Ndiaye', 'Senegal', 'ATA', 12),
  ('I. Ndiaye', 'Senegal', 'ATA', 13),
  ('O. Niang', 'Senegal', 'ATA', 22),
  ('C. Sabaly', 'Senegal', 'ATA', 21),
  ('I. Sarr', 'Senegal', 'ATA', 18),
  ('M. Keller', 'Switzerland', 'GOL', 21),
  ('G. Kobel', 'Switzerland', 'GOL', 1),
  ('Y. Mvogo', 'Switzerland', 'GOL', 12),
  ('M. Akanji', 'Switzerland', 'DEF', 5),
  ('A. Amenda', 'Switzerland', 'DEF', 18),
  ('E. Cömert', 'Switzerland', 'DEF', 18),
  ('N. Elvedi', 'Switzerland', 'DEF', 4),
  ('L. Jaquez', 'Switzerland', 'DEF', 20),
  ('M. Muheim', 'Switzerland', 'DEF', 2),
  ('R. Rodríguez', 'Switzerland', 'DEF', 13),
  ('S. Widmer', 'Switzerland', 'DEF', 3),
  ('M. Aebischer', 'Switzerland', 'MEI', 20),
  ('R. Freuler', 'Switzerland', 'MEI', 8),
  ('A. Jashari', 'Switzerland', 'MEI', 20),
  ('J. Manzambi', 'Switzerland', 'MEI', 9),
  ('Joël Monteiro', 'Switzerland', 'MEI', 14),
  ('A. Sanches', 'Switzerland', 'MEI', 10),
  ('V. Sierro', 'Switzerland', 'MEI', 16),
  ('D. Sow', 'Switzerland', 'MEI', 15),
  ('R. Vargas', 'Switzerland', 'MEI', 17),
  ('G. Xhaka', 'Switzerland', 'MEI', 10),
  ('D. Zakaria', 'Switzerland', 'MEI', 6),
  ('B. Embolo', 'Switzerland', 'ATA', 7),
  ('D. Ndoye', 'Switzerland', 'ATA', 11),
  ('N. Okafor', 'Switzerland', 'ATA', 9),
  ('F. Rieder', 'Switzerland', 'ATA', 22),
  ('C. Acevedo', 'Mexico', 'GOL', 12),
  ('L. Malagón', 'Mexico', 'GOL', 1),
  ('G. Ochoa', 'Mexico', 'GOL', 13),
  ('J. Rangel', 'Mexico', 'GOL', 1),
  ('E.  Águila', 'Mexico', 'DEF', 21),
  ('K. Álvarez', 'Mexico', 'DEF', 3),
  ('J. Angulo', 'Mexico', 'DEF', 14),
  ('D. Campillo', 'Mexico', 'DEF', NULL),
  ('J. Gallardo', 'Mexico', 'DEF', 23),
  ('J. Garza', 'Mexico', 'DEF', NULL),
  ('V. Guzmán', 'Mexico', 'DEF', 22),
  ('R. Juárez', 'Mexico', 'DEF', 15),
  ('C. Montes', 'Mexico', 'DEF', 3),
  ('J. Orozco', 'Mexico', 'DEF', 19),
  ('I. Reyes', 'Mexico', 'DEF', 15),
  ('J. Sánchez', 'Mexico', 'DEF', 2),
  ('J. Vásquez', 'Mexico', 'DEF', 5),
  ('E. López', 'Mexico', 'DEF', 2),
  ('R. Alvarado', 'Mexico', 'ATA', 25),
  ('E. Álvarez', 'Mexico', 'MEI', 4),
  ('F. Ambríz', 'Mexico', 'MEI', 6),
  ('K. Castañeda', 'Mexico', 'MEI', 9),
  ('M. Chávez', 'Mexico', 'DEF', 20),
  ('Álvaro Fidalgo', 'Mexico', 'MEI', NULL),
  ('Iker Jareth Fimbres Ochoa', 'Mexico', 'MEI', 8),
  ('D. García', 'Mexico', 'MEI', 8),
  ('B. González', 'Mexico', 'MEI', 26),
  ('B. Gutiérrez', 'Mexico', 'MEI', 26),
  ('A. Gutiérrez', 'Mexico', 'MEI', 15),
  ('R. Ledezma', 'Mexico', 'MEI', 20),
  ('É. Lira', 'Mexico', 'MEI', 6),
  ('G. Mora', 'Mexico', 'MEI', 19),
  ('O. Pineda', 'Mexico', 'MEI', 17),
  ('C. Rodríguez', 'Mexico', 'MEI', 8),
  ('L. Romo', 'Mexico', 'DEF', 7),
  ('M. Ruiz', 'Mexico', 'MEI', 14),
  ('É. Sánchez', 'Mexico', 'MEI', 14),
  ('O. Vargas', 'Mexico', 'MEI', 18),
  ('G. Berterame', 'Mexico', 'ATA', 17),
  ('A. González', 'Mexico', 'ATA', 14),
  ('R. Jiménez', 'Mexico', 'ATA', 9),
  ('D. Lainez', 'Mexico', 'ATA', 16),
  ('H. Lozano', 'Mexico', 'ATA', 22),
  ('G. Martínez', 'Mexico', 'ATA', 22),
  ('J. Quiñones', 'Mexico', 'ATA', 16),
  ('J. Ruvalcaba', 'Mexico', 'ATA', 17),
  ('Á. Sepúlveda', 'Mexico', 'ATA', 18),
  ('A. Vega', 'Mexico', 'ATA', 10),
  ('Jo Hyeon-Woo', 'South Korea', 'GOL', 21),
  ('Kim Seung-Gyu', 'South Korea', 'GOL', 1),
  ('Song Bum-Keun', 'South Korea', 'GOL', 1),
  ('Cho Yu-Min', 'South Korea', 'DEF', 14),
  ('Kim Min-Jae', 'South Korea', 'DEF', 4),
  ('Kim Moon-Hwan', 'South Korea', 'DEF', 15),
  ('Kim Tae-Hyeon', 'South Korea', 'DEF', 26),
  ('Lee Gi-Hyuk', 'South Korea', 'DEF', 13),
  ('Lee Han-Beom', 'South Korea', 'DEF', 16),
  ('Lee Tae-Seok', 'South Korea', 'DEF', 3),
  ('Seol Young-Woo', 'South Korea', 'DEF', 22),
  ('Bae Jun-Ho', 'South Korea', 'MEI', 17),
  ('J. Castrop', 'South Korea', 'MEI', 13),
  ('Eom Ji-Sung', 'South Korea', 'MEI', 18),
  ('Hwang In-Beom', 'South Korea', 'MEI', 6),
  ('Kim Jin-Gyu', 'South Korea', 'MEI', 6),
  ('Lee Dong-Gyeong', 'South Korea', 'MEI', 10),
  ('Lee Jae-Sung', 'South Korea', 'MEI', 10),
  ('Lee Kang-In', 'South Korea', 'MEI', 18),
  ('Paik Seung-Ho', 'South Korea', 'MEI', 5),
  ('Park Jin-Seop', 'South Korea', 'MEI', 5),
  ('Yang Hyun-Jun', 'South Korea', 'MEI', 15),
  ('Cho Gue-Sung', 'South Korea', 'ATA', 9),
  ('Hwang Hee-Chan', 'South Korea', 'ATA', 11),
  ('Oh Hyeon-Gyu', 'South Korea', 'ATA', 9),
  ('Son Heung-Min', 'South Korea', 'ATA', 7),
  ('P. Beach', 'Australia', 'GOL', 12),
  ('P. Izzo', 'Australia', 'GOL', 12),
  ('M. Ryan', 'Australia', 'GOL', 1),
  ('A. Behich', 'Australia', 'DEF', 16),
  ('J. Bos', 'Australia', 'DEF', 5),
  ('C. Burgess', 'Australia', 'DEF', 21),
  ('A. Circati', 'Australia', 'DEF', 23),
  ('J. Geria', 'Australia', 'DEF', 22),
  ('L. Herrington', 'Australia', 'DEF', 13),
  ('K. Rowles', 'Australia', 'DEF', 4),
  ('M. Degenek', 'Australia', 'MEI', 2),
  ('A. Hrustić', 'Australia', 'MEI', 10),
  ('J. Italiano', 'Australia', 'MEI', 17),
  ('R. McGree', 'Australia', 'MEI', 14),
  ('A. O&apos;Neill', 'Australia', 'MEI', 13),
  ('Paul Michael Junior Okon-Engstler', 'Australia', 'MEI', 6),
  ('A. Robertson', 'Australia', 'MEI', NULL),
  ('K. Trewin', 'Australia', 'MEI', 7),
  ('P. Yazbek', 'Australia', 'MEI', 19),
  ('M. Boyle', 'Australia', 'ATA', 6),
  ('N. Irankunda', 'Australia', 'ATA', 11),
  ('D. Jurić', 'Australia', 'ATA', 19),
  ('A. Mabil', 'Australia', 'ATA', 10),
  ('C. Metcalfe', 'Australia', 'ATA', 8),
  ('A. Šuto', 'Australia', 'ATA', NULL),
  ('N. Velupillay', 'Australia', 'ATA', 7),
  ('A. Beiranvand', 'Iran', 'GOL', 1),
  ('H. Hosseini', 'Iran', 'GOL', 22),
  ('P. Niazmand', 'Iran', 'GOL', 1),
  ('A. Abdullayev', 'Iran', 'DEF', 23),
  ('M. Ghorbani', 'Iran', 'DEF', 26),
  ('E. Hajisafi', 'Iran', 'DEF', 3),
  ('Saleh Hardani', 'Iran', 'DEF', 5),
  ('H. Kanani', 'Iran', 'DEF', 13),
  ('S. Khalilzadeh', 'Iran', 'DEF', 4),
  ('M. Mohammadi', 'Iran', 'DEF', 5),
  ('A. Nemati', 'Iran', 'DEF', 5),
  ('R. Rezaeian', 'Iran', 'DEF', 23),
  ('A. Yousefi', 'Iran', 'DEF', 18),
  ('S. Ghoddos', 'Iran', 'MEI', 14),
  ('A. Gholizadeh', 'Iran', 'MEI', 11),
  ('O. Noorafkan', 'Iran', 'MEI', 21),
  ('A. Razzaghinia', 'Iran', 'MEI', 6),
  ('A. Alipour', 'Iran', 'ATA', 8),
  ('M. Hashemnejad', 'Iran', 'ATA', 16),
  ('A. Hosseinzadeh', 'Iran', 'ATA', 10),
  ('A. Jahanbakhsh', 'Iran', 'ATA', 7),
  ('A. Mahmoudi', 'Iran', 'ATA', NULL),
  ('S. Moghanlou', 'Iran', 'ATA', 24),
  ('M. Mohebi', 'Iran', 'ATA', 27),
  ('M. Taremi', 'Iran', 'ATA', 9),
  ('Nawaf Al Aqidi', 'Saudi Arabia', 'GOL', 1),
  ('Ahmed Al Kassar', 'Saudi Arabia', 'GOL', 22),
  ('Raghed Najjar', 'Saudi Arabia', 'GOL', 22),
  ('Mohammed Al Owais', 'Saudi Arabia', 'GOL', 21),
  ('M. Al Rubaie', 'Saudi Arabia', 'GOL', 22),
  ('Abdulrahman Al Sanbi', 'Saudi Arabia', 'GOL', 21),
  ('Saud Abdulhamid', 'Saudi Arabia', 'DEF', 12),
  ('Nawaf Boushal', 'Saudi Arabia', 'DEF', 13),
  ('Waleed Al Ahmad', 'Saudi Arabia', 'DEF', 14),
  ('Abdulelah Al Amri', 'Saudi Arabia', 'DEF', 4),
  ('Khalifah Al Dawsari', 'Saudi Arabia', 'DEF', 4),
  ('Muteb Al Mufarrij', 'Saudi Arabia', 'DEF', 4),
  ('Mohammed Essa Harbush', 'Saudi Arabia', 'DEF', 5),
  ('R. Hamidou', 'Saudi Arabia', 'DEF', 2),
  ('Hassan Kadesh', 'Saudi Arabia', 'DEF', 14),
  ('Ali Lajami', 'Saudi Arabia', 'DEF', 3),
  ('Ali Majrashi', 'Saudi Arabia', 'DEF', 2),
  ('Mohammed Bakor', 'Saudi Arabia', 'DEF', 17),
  ('Hassan Tambakti', 'Saudi Arabia', 'DEF', 5),
  ('J. Thakri', 'Saudi Arabia', 'DEF', 3),
  ('Mohammed Abu Al Shamat', 'Saudi Arabia', 'MEI', 12),
  ('Waheb Saleh', 'Saudi Arabia', 'MEI', 18),
  ('Turki Al Ammar', 'Saudi Arabia', 'MEI', 19),
  ('Nasser Al Dawsari', 'Saudi Arabia', 'MEI', 6),
  ('Salem Al Dawsari', 'Saudi Arabia', 'MEI', 10),
  ('Salman Al Faraj', 'Saudi Arabia', 'MEI', 7),
  ('Murad Al Hawsawi', 'Saudi Arabia', 'MEI', 16),
  ('Ziyad Al Johani', 'Saudi Arabia', 'MEI', 8),
  ('Musab Al Juwayr', 'Saudi Arabia', 'MEI', 10),
  ('Abdullah Al Khaibari', 'Saudi Arabia', 'MEI', 15),
  ('Mohammed Al-Majhad', 'Saudi Arabia', 'MEI', 20),
  ('Mohamed Kanno', 'Saudi Arabia', 'MEI', 23),
  ('Mohammed Mater Mohsin Mahzari', 'Saudi Arabia', 'MEI', 23),
  ('N. Masoud', 'Saudi Arabia', 'MEI', 6),
  ('A. S. Al Aliwa', 'Saudi Arabia', 'ATA', 7),
  ('Feras Al Brikan', 'Saudi Arabia', 'ATA', 9),
  ('Khalid Al Ghannam', 'Saudi Arabia', 'ATA', 16),
  ('Abdullah Al Hamdan', 'Saudi Arabia', 'ATA', 19),
  ('Abdulrahman Al Obud', 'Saudi Arabia', 'ATA', 20),
  ('Marwan Al Sahafi', 'Saudi Arabia', 'ATA', 20),
  ('Saleh Al Shehri', 'Saudi Arabia', 'ATA', 11),
  ('Sultan Mandash', 'Saudi Arabia', 'ATA', NULL),
  ('Ayman Yahya', 'Saudi Arabia', 'ATA', 8),
  ('O. Baumann', 'Germany', 'GOL', 1),
  ('F. Dahmen', 'Germany', 'GOL', 21),
  ('A. Nübel', 'Germany', 'GOL', 12),
  ('W. Anton', 'Germany', 'DEF', 3),
  ('N. Brown', 'Germany', 'DEF', 18),
  ('D. Raum', 'Germany', 'DEF', 22),
  ('A. Rüdiger', 'Germany', 'DEF', 2),
  ('N. Schlotterbeck', 'Germany', 'DEF', 15),
  ('J. Tah', 'Germany', 'DEF', 4),
  ('M. Thiaw', 'Germany', 'DEF', 2),
  ('J. Vagnoman', 'Germany', 'DEF', 2),
  ('L. Goretzka', 'Germany', 'MEI', 8),
  ('P. Groß', 'Germany', 'MEI', 5),
  ('L. Karl', 'Germany', 'MEI', 21),
  ('J. Kimmich', 'Germany', 'MEI', 6),
  ('K. Schade', 'Germany', 'MEI', 16),
  ('A. Stach', 'Germany', 'MEI', 23),
  ('A. Stiller', 'Germany', 'MEI', 16),
  ('F. Wirtz', 'Germany', 'MEI', 17),
  ('C. Führich', 'Germany', 'ATA', 11),
  ('S. Gnabry', 'Germany', 'ATA', 20),
  ('K. Havertz', 'Germany', 'ATA', 7),
  ('L. Sané', 'Germany', 'ATA', 19),
  ('D. Undav', 'Germany', 'ATA', 13),
  ('N. Woltemade', 'Germany', 'ATA', 11),
  ('E. Martínez', 'Argentina', 'GOL', 23),
  ('J. Musso', 'Argentina', 'GOL', 23),
  ('G. Rulli', 'Argentina', 'GOL', 12),
  ('M. Acuña', 'Argentina', 'DEF', 8),
  ('A. Giay', 'Argentina', 'DEF', 4),
  ('L. Martínez', 'Argentina', 'DEF', 2),
  ('N. Molina', 'Argentina', 'DEF', 16),
  ('N. Otamendi', 'Argentina', 'DEF', 19),
  ('G. Rojas', 'Argentina', 'DEF', NULL),
  ('C. Romero', 'Argentina', 'DEF', 13),
  ('M. Senesi', 'Argentina', 'DEF', 6),
  ('N. Tagliafico', 'Argentina', 'DEF', 3),
  ('V. Barco', 'Argentina', 'MEI', 3),
  ('E. Fernández', 'Argentina', 'MEI', 8),
  ('A. Mac Allister', 'Argentina', 'MEI', 20),
  ('E. Palacios', 'Argentina', 'MEI', 14),
  ('L. Paredes', 'Argentina', 'MEI', 5),
  ('N. Paz', 'Argentina', 'MEI', 18),
  ('M. Perrone', 'Argentina', 'MEI', 22),
  ('R. De Paul', 'Argentina', 'MEI', 7),
  ('T. Almada', 'Argentina', 'ATA', 16),
  ('J. Álvarez', 'Argentina', 'ATA', 9),
  ('N. González', 'Argentina', 'ATA', 15),
  ('J. López', 'Argentina', 'ATA', 13),
  ('Franco Mastantuono', 'Argentina', 'ATA', 10),
  ('L. Messi', 'Argentina', 'ATA', 10),
  ('G. Prestianni', 'Argentina', 'ATA', 20),
  ('G. Simeone', 'Argentina', 'ATA', 17),
  ('José Sá', 'Portugal', 'GOL', 12),
  ('Rui Silva', 'Portugal', 'GOL', 22),
  ('Ricardo Velho', 'Portugal', 'GOL', 12),
  ('Tomás Araújo', 'Portugal', 'DEF', 3),
  ('João Cancelo', 'Portugal', 'DEF', 20),
  ('Diogo Dalot', 'Portugal', 'DEF', 5),
  ('Gonçalo Inácio', 'Portugal', 'DEF', 14),
  ('Nuno Mendes', 'Portugal', 'DEF', 19),
  ('António Silva', 'Portugal', 'DEF', 4),
  ('Renato Veiga', 'Portugal', 'DEF', 13),
  ('Bruno Fernandes', 'Portugal', 'MEI', 8),
  ('Mateus Fernandes', 'Portugal', 'MEI', 8),
  ('João Neves', 'Portugal', 'MEI', 15),
  ('Rúben Neves', 'Portugal', 'MEI', 21),
  ('Matheus Nunes', 'Portugal', 'MEI', 18),
  ('Pote', 'Portugal', 'MEI', 17),
  ('Samú Costa', 'Portugal', 'MEI', 6),
  ('Vitinha', 'Portugal', 'MEI', 23),
  ('Francisco Conceição', 'Portugal', 'ATA', 19),
  ('Gonçalo Guedes', 'Portugal', 'ATA', 17),
  ('Ricardo Horta', 'Portugal', 'ATA', 15),
  ('João Félix', 'Portugal', 'ATA', 11),
  ('Pedro Neto', 'Portugal', 'ATA', 18),
  ('Paulinho', 'Portugal', 'ATA', 9),
  ('Gonçalo Ramos', 'Portugal', 'ATA', 9),
  ('Trincão', 'Portugal', 'ATA', 16),
  ('S. Ben Hsan', 'Tunisia', 'GOL', 16),
  ('C. Abdelmouhib', 'Tunisia', 'GOL', NULL),
  ('A. Dahmen', 'Tunisia', 'GOL', 16),
  ('A. Abdi', 'Tunisia', 'DEF', 2),
  ('A. Arous', 'Tunisia', 'DEF', 24),
  ('A. Ben Hmida', 'Tunisia', 'DEF', 3),
  ('D. Bronn', 'Tunisia', 'DEF', 6),
  ('R. Chikhaoui', 'Tunisia', 'DEF', NULL),
  ('M. Neffati', 'Tunisia', 'DEF', 17),
  ('O. Rekik', 'Tunisia', 'DEF', 4),
  ('M. Talbi', 'Tunisia', 'DEF', 3),
  ('Y. Valery', 'Tunisia', 'DEF', 20),
  ('H. Mahmoud', 'Tunisia', 'MEI', 15),
  ('M. Ben Ouanes', 'Tunisia', 'MEI', 21),
  ('Ismaël Gharbi', 'Tunisia', 'MEI', 11),
  ('R. Khedira', 'Tunisia', 'MEI', 18),
  ('H. Mejbri', 'Tunisia', 'MEI', 10),
  ('E. Skhiri', 'Tunisia', 'MEI', 17),
  ('A. Ben Slimane', 'Tunisia', 'MEI', 8),
  ('E. Achouri', 'Tunisia', 'ATA', 7),
  ('K. Ayari', 'Tunisia', 'ATA', 10),
  ('F. Chaouat', 'Tunisia', 'ATA', 19),
  ('R. Elloumi', 'Tunisia', 'ATA', NULL),
  ('H. Mastouri', 'Tunisia', 'ATA', 9),
  ('E. Saad', 'Tunisia', 'ATA', 8),
  ('S. Tounekti', 'Tunisia', 'ATA', 26),
  ('M. Harrar', 'Morocco', 'GOL', 22),
  ('M. Benabid', 'Morocco', 'GOL', 12),
  ('Y. Bounou', 'Morocco', 'GOL', 1),
  ('M. Mohamedi', 'Morocco', 'GOL', 12),
  ('N. Aguerd', 'Morocco', 'DEF', 5),
  ('A. Ait Boudlal', 'Morocco', 'DEF', 27),
  ('I. Baouf', 'Morocco', 'DEF', 4),
  ('M. Chibi', 'Morocco', 'DEF', 15),
  ('I. Diop', 'Morocco', 'DEF', 3),
  ('S. El Karouani', 'Morocco', 'DEF', 3),
  ('Z. El Ouahdi', 'Morocco', 'DEF', 11),
  ('J. El Yamiq', 'Morocco', 'DEF', 18),
  ('A. Hakimi', 'Morocco', 'DEF', 2),
  ('R. Halhal', 'Morocco', 'DEF', 4),
  ('N. Mazraoui', 'Morocco', 'DEF', 3),
  ('C. Riad', 'Morocco', 'DEF', 6),
  ('A. Salah-Eddine', 'Morocco', 'DEF', 26),
  ('A. Adli', 'Morocco', 'MEI', 21),
  ('S. Amrabat', 'Morocco', 'MEI', 4),
  ('Y. Belammari', 'Morocco', 'MEI', 28),
  ('Rayane Bounida', 'Morocco', 'MEI', 15),
  ('Brahim Díaz', 'Morocco', 'MEI', 10),
  ('N. El Aynaoui', 'Morocco', 'MEI', 24),
  ('B. El Khannouss', 'Morocco', 'MEI', 23),
  ('S. El Mourabet', 'Morocco', 'MEI', NULL),
  ('M. Hrimat', 'Morocco', 'MEI', 6),
  ('A. Ounahi', 'Morocco', 'MEI', 8),
  ('I. Saibari', 'Morocco', 'MEI', 11),
  ('O. Targhalline', 'Morocco', 'MEI', 14),
  ('Gessime Yassine', 'Morocco', 'MEI', 17),
  ('Ilias Akhomach', 'Morocco', 'ATA', 16),
  ('E. Ben Seghir', 'Morocco', 'ATA', 13),
  ('A. El Kaabi', 'Morocco', 'ATA', 20),
  ('Y. En-Nesyri', 'Morocco', 'ATA', 19),
  ('A. Ezzalzouli', 'Morocco', 'ATA', 17),
  ('H. Igamane', 'Morocco', 'ATA', 7),
  ('S. Rahimi', 'Morocco', 'ATA', 9),
  ('C. Talbi', 'Morocco', 'ATA', 21),
  ('M. Zabiri', 'Morocco', 'ATA', 21),
  ('M. Alaa', 'Egypt', 'GOL', NULL),
  ('Ahmed El Shenawy', 'Egypt', 'GOL', 1),
  ('Mohamed El Shenawy', 'Egypt', 'GOL', 23),
  ('Mostafa Shobeir', 'Egypt', 'GOL', 26),
  ('Mohamed Sobhi', 'Egypt', 'GOL', 16),
  ('Al Mahdi Soliman', 'Egypt', 'GOL', 16),
  ('Hossam Abdelmaguid', 'Egypt', 'DEF', 4),
  ('Mohamed Abdelmonem', 'Egypt', 'DEF', 6),
  ('Ahmed Eid', 'Egypt', 'DEF', 24),
  ('Ahmed Abou El Fotouh', 'Egypt', 'DEF', 13),
  ('M. Hamdi', 'Egypt', 'DEF', 12),
  ('Mohamed Hany', 'Egypt', 'DEF', 3),
  ('Yasser Ibrahim', 'Egypt', 'DEF', 6),
  ('M. Ismail', 'Egypt', 'DEF', 28),
  ('Rami Rabia', 'Egypt', 'DEF', 5),
  ('Khaled Sobhy', 'Egypt', 'DEF', 2),
  ('T. Alaa', 'Egypt', 'MEI', NULL),
  ('Emam Ashour', 'Egypt', 'MEI', 8),
  ('Marwan Attia', 'Egypt', 'MEI', 19),
  ('Hamdi Fathy', 'Egypt', 'MEI', 14),
  ('Islam Issa', 'Egypt', 'MEI', 8),
  ('Ahmed Koka', 'Egypt', 'MEI', 15),
  ('Mohanad Lasheen', 'Egypt', 'MEI', 17),
  ('Mahmoud Saber', 'Egypt', 'MEI', 27),
  ('Mohamed Shehata', 'Egypt', 'MEI', 15),
  ('Trézéguet', 'Egypt', 'MEI', 7),
  ('Ibrahim Adel', 'Egypt', 'ATA', 20),
  ('Osama Faisal', 'Egypt', 'ATA', 21),
  ('Mostafa Fathi', 'Egypt', 'ATA', 18),
  ('H. Hassan', 'Egypt', 'ATA', 15),
  ('N. Mansy', 'Egypt', 'ATA', 21),
  ('Omar Marmoush', 'Egypt', 'ATA', 22),
  ('Salah Mohsen', 'Egypt', 'ATA', 9),
  ('Mostafa Mohamed', 'Egypt', 'ATA', 11),
  ('Mohamed Salah', 'Egypt', 'ATA', 10),
  ('Zizo', 'Egypt', 'ATA', 25),
  ('L. Horníček', 'Czech Republic', 'GOL', 16),
  ('M. Jedlička', 'Czech Republic', 'GOL', 23),
  ('M. Kovář', 'Czech Republic', 'GOL', 1),
  ('Š. Chaloupek', 'Czech Republic', 'DEF', 2),
  ('V. Coufal', 'Czech Republic', 'DEF', 5),
  ('T. Holeš', 'Czech Republic', 'DEF', 3),
  ('R. Hranáč', 'Czech Republic', 'DEF', 4),
  ('D. Jurásek', 'Czech Republic', 'DEF', 17),
  ('L. Krejčí', 'Czech Republic', 'DEF', 7),
  ('M. Vitík', 'Czech Republic', 'DEF', 6),
  ('J. Zelený', 'Czech Republic', 'DEF', 20),
  ('L. Červ', 'Czech Republic', 'MEI', 12),
  ('V. Darida', 'Czech Republic', 'MEI', 8),
  ('A. Karabec', 'Czech Republic', 'MEI', 9),
  ('L. Provod', 'Czech Republic', 'MEI', 14),
  ('M. Sadílek', 'Czech Republic', 'MEI', 18),
  ('T. Souček', 'Czech Republic', 'MEI', 22),
  ('P. Šulc', 'Czech Republic', 'MEI', 15),
  ('T. Chorý', 'Czech Republic', 'ATA', 19),
  ('M. Chytil', 'Czech Republic', 'ATA', 13),
  ('J. Kliment', 'Czech Republic', 'ATA', 11),
  ('P. Schick', 'Czech Republic', 'ATA', 10),
  ('D. Višinský', 'Czech Republic', 'ATA', 21),
  ('P. Pentz', 'Austria', 'GOL', 13),
  ('A. Schlager', 'Austria', 'GOL', 1),
  ('F. Wiegele', 'Austria', 'GOL', NULL),
  ('D. Affengruber', 'Austria', 'DEF', 20),
  ('D. Alaba', 'Austria', 'DEF', 8),
  ('K. Danso', 'Austria', 'DEF', 3),
  ('M. Friedl', 'Austria', 'DEF', 2),
  ('P. Lienhart', 'Austria', 'DEF', 15),
  ('P. Mwene', 'Austria', 'DEF', 16),
  ('S. Posch', 'Austria', 'DEF', 5),
  ('M. Svoboda', 'Austria', 'DEF', 3),
  ('C. Baumgartner', 'Austria', 'MEI', 19),
  ('C. Chukwuemeka', 'Austria', 'MEI', 10),
  ('F. Grillitsch', 'Austria', 'MEI', 10),
  ('K. Laimer', 'Austria', 'MEI', 20),
  ('A. Prass', 'Austria', 'MEI', 8),
  ('M. Sabitzer', 'Austria', 'MEI', 9),
  ('X. Schlager', 'Austria', 'MEI', 4),
  ('R. Schmid', 'Austria', 'MEI', 18),
  ('N. Seiwald', 'Austria', 'MEI', 6),
  ('P. Wanner', 'Austria', 'MEI', 10),
  ('P. Wimmer', 'Austria', 'MEI', 21),
  ('M. Arnautović', 'Austria', 'ATA', 7),
  ('M. Gregoritsch', 'Austria', 'ATA', 11),
  ('S. Kalajdzic', 'Austria', 'ATA', 21),
  ('A. Bayındır', 'Turkey', 'GOL', 12),
  ('U. Çakır', 'Turkey', 'GOL', 23),
  ('E. Destanoğlu', 'Turkey', 'GOL', 1),
  ('M. Günok', 'Turkey', 'GOL', 1),
  ('M. Şengezer', 'Turkey', 'GOL', 1),
  ('S. Akaydin', 'Turkey', 'DEF', 4),
  ('Yusuf Akçiçek', 'Turkey', 'DEF', 14),
  ('K. Ayhan', 'Turkey', 'DEF', 22),
  ('A. Bardakcı', 'Turkey', 'DEF', 14),
  ('Z. Çelik', 'Turkey', 'DEF', 2),
  ('E. Elmalı', 'Turkey', 'DEF', 3),
  ('O. Kabak', 'Turkey', 'DEF', 15),
  ('F. Kadıoğlu', 'Turkey', 'DEF', 20),
  ('A. Kaplan', 'Turkey', 'DEF', 13),
  ('M. Müldür', 'Turkey', 'DEF', 18),
  ('Ç. Söyüncü', 'Turkey', 'DEF', 4),
  ('O. Aydın', 'Turkey', 'MEI', 19),
  ('H. Çalhanoğlu', 'Turkey', 'MEI', 10),
  ('A. Güler', 'Turkey', 'MEI', 8),
  ('A. Karazor', 'Turkey', 'MEI', 19),
  ('O. Kökçü', 'Turkey', 'MEI', 6),
  ('S. Özcan', 'Turkey', 'MEI', 5),
  ('E. Tıknaz', 'Turkey', 'MEI', 6),
  ('C. Uzun', 'Turkey', 'MEI', 22),
  ('İ. Yüksek', 'Turkey', 'MEI', 16),
  ('Y. Akgün', 'Turkey', 'ATA', 21),
  ('K. Aktürkoğlu', 'Turkey', 'ATA', 7),
  ('D. Gül', 'Turkey', 'ATA', 13),
  ('İ. Kahveci', 'Turkey', 'ATA', 17),
  ('Y. Sarı', 'Turkey', 'ATA', 7),
  ('A. Şimşir', 'Turkey', 'ATA', 20),
  ('K. Yıldız', 'Turkey', 'ATA', 11),
  ('B. Yılmaz', 'Turkey', 'ATA', 9),
  ('V. Myhra', 'Norway', 'GOL', 13),
  ('Ø. Nyland', 'Norway', 'GOL', 1),
  ('E. Selvik', 'Norway', 'GOL', 13),
  ('K. Ajer', 'Norway', 'DEF', 3),
  ('F. Bjørkan', 'Norway', 'DEF', 15),
  ('O. Bjørtuft', 'Norway', 'DEF', 4),
  ('H. Falchener', 'Norway', 'DEF', NULL),
  ('T. Heggem', 'Norway', 'DEF', 17),
  ('L. Østigård', 'Norway', 'DEF', 4),
  ('M. Pedersen', 'Norway', 'DEF', 16),
  ('J. Ryerson', 'Norway', 'DEF', 14),
  ('D. Møller Wolfe', 'Norway', 'DEF', 5),
  ('P. Berg', 'Norway', 'MEI', 6),
  ('S. Berge', 'Norway', 'MEI', 8),
  ('Oscar Bobb', 'Norway', 'MEI', 22),
  ('F. Myhre', 'Norway', 'MEI', 16),
  ('M. Thorsby', 'Norway', 'MEI', 2),
  ('K. Thorstvedt', 'Norway', 'MEI', 18),
  ('E. Haaland', 'Norway', 'ATA', 9),
  ('J. Hauge', 'Norway', 'ATA', 15),
  ('J. Strand Larsen', 'Norway', 'ATA', 11),
  ('A. Nusa', 'Norway', 'ATA', 20),
  ('A. Schjelderup', 'Norway', 'ATA', 10),
  ('A. Sørloth', 'Norway', 'ATA', 7),
  ('S. Bain', 'Scotland', 'GOL', 21),
  ('A. Gunn', 'Scotland', 'GOL', 1),
  ('L. Kelly', 'Scotland', 'GOL', 12),
  ('G. Hanley', 'Scotland', 'DEF', 5),
  ('J. Hendry', 'Scotland', 'DEF', 13),
  ('D. Hyam', 'Scotland', 'DEF', 5),
  ('R. McCrorie', 'Scotland', 'DEF', 21),
  ('S. McKenna', 'Scotland', 'DEF', 16),
  ('N. Patterson', 'Scotland', 'DEF', 22),
  ('A. Ralston', 'Scotland', 'DEF', 22),
  ('A. Robertson', 'Scotland', 'DEF', 3),
  ('J. Souttar', 'Scotland', 'DEF', 15),
  ('K. Tierney', 'Scotland', 'DEF', 6),
  ('R. Christie', 'Scotland', 'MEI', 11),
  ('Findlay Curtis', 'Scotland', 'MEI', 22),
  ('L. Ferguson', 'Scotland', 'MEI', 19),
  ('B. Gilmour', 'Scotland', 'MEI', 8),
  ('A. Irving', 'Scotland', 'MEI', 8),
  ('J.  McGinn', 'Scotland', 'MEI', 7),
  ('K. McLean', 'Scotland', 'MEI', 23),
  ('S. McTominay', 'Scotland', 'MEI', 4),
  ('L. Miller', 'Scotland', 'MEI', 14),
  ('C. Adams', 'Scotland', 'ATA', 10),
  ('T. Conway', 'Scotland', 'ATA', 9),
  ('B. Doak', 'Scotland', 'ATA', 17),
  ('L. Dykes', 'Scotland', 'ATA', 9),
  ('G. Hirst', 'Scotland', 'ATA', 18),
  ('O. Hadžikić', 'Bosnia & Herzegovina', 'GOL', 12),
  ('N. Vasilj', 'Bosnia & Herzegovina', 'GOL', 1),
  ('M. Zlomislić', 'Bosnia & Herzegovina', 'GOL', 22),
  ('D. Burnić', 'Bosnia & Herzegovina', 'DEF', 17),
  ('N. Äelik', 'Bosnia & Herzegovina', 'DEF', 3),
  ('A. Dedić', 'Bosnia & Herzegovina', 'DEF', 7),
  ('N. Katić', 'Bosnia & Herzegovina', 'DEF', 18),
  ('S. Kolašinac', 'Bosnia & Herzegovina', 'DEF', 5),
  ('T. Muharemović', 'Bosnia & Herzegovina', 'DEF', 4),
  ('N. Mujakić', 'Bosnia & Herzegovina', 'DEF', 2),
  ('S. Radeljić', 'Bosnia & Herzegovina', 'DEF', 21),
  ('I. Bašić', 'Bosnia & Herzegovina', 'MEI', 13),
  ('A. Gigović', 'Bosnia & Herzegovina', 'MEI', 8),
  ('A. Hadžiahmetović', 'Bosnia & Herzegovina', 'MEI', 16),
  ('Ermin Mahmić', 'Bosnia & Herzegovina', 'MEI', 20),
  ('I. Šunjić', 'Bosnia & Herzegovina', 'MEI', 14),
  ('B. Tahirović', 'Bosnia & Herzegovina', 'MEI', 6),
  ('Kerim-Sam Alajbegović', 'Bosnia & Herzegovina', 'ATA', 19),
  ('E. Bajraktarevic', 'Bosnia & Herzegovina', 'ATA', 20),
  ('S. Baždar', 'Bosnia & Herzegovina', 'ATA', 9),
  ('E. Demirović', 'Bosnia & Herzegovina', 'ATA', 10),
  ('E. Džeko', 'Bosnia & Herzegovina', 'ATA', 11),
  ('J. Lukić', 'Bosnia & Herzegovina', 'ATA', 19),
  ('A. Memić', 'Bosnia & Herzegovina', 'ATA', 15),
  ('H. Tabaković', 'Bosnia & Herzegovina', 'ATA', 23),
  ('J. Bijlow', 'Netherlands', 'GOL', 13),
  ('M. Flekken', 'Netherlands', 'GOL', 23),
  ('B. Verbruggen', 'Netherlands', 'GOL', 1),
  ('N. Aké', 'Netherlands', 'DEF', 5),
  ('D. Dumfries', 'Netherlands', 'DEF', 22),
  ('L. Geertruida', 'Netherlands', 'DEF', 2),
  ('J. Hato', 'Netherlands', 'DEF', 4),
  ('S. de Vrij', 'Netherlands', 'DEF', 6),
  ('V. van Dijk', 'Netherlands', 'DEF', 4),
  ('J. van Hecke', 'Netherlands', 'DEF', 12),
  ('M. van de Ven', 'Netherlands', 'DEF', 15),
  ('J. Frimpong', 'Netherlands', 'MEI', 12),
  ('R. Gravenberch', 'Netherlands', 'MEI', 8),
  ('T. Koopmeiners', 'Netherlands', 'MEI', 20),
  ('T. Reijnders', 'Netherlands', 'MEI', 14),
  ('J. Schouten', 'Netherlands', 'MEI', 16),
  ('X. Simons', 'Netherlands', 'MEI', 7),
  ('K. Smit', 'Netherlands', 'MEI', 8),
  ('Q. Timber', 'Netherlands', 'MEI', 12),
  ('L. Valente', 'Netherlands', 'MEI', 22),
  ('B. Brobbey', 'Netherlands', 'ATA', 9),
  ('C. Gakpo', 'Netherlands', 'ATA', 11),
  ('N. Lang', 'Netherlands', 'ATA', 17),
  ('D. Malen', 'Netherlands', 'ATA', 18),
  ('W. Weghorst', 'Netherlands', 'ATA', 9),
  ('Y. Fofana', 'Ivory Coast', 'GOL', 1),
  ('M. Koné', 'Ivory Coast', 'GOL', 16),
  ('A. Lafont', 'Ivory Coast', 'GOL', 23),
  ('E. Agbadou', 'Ivory Coast', 'DEF', 20),
  ('C. Akpa', 'Ivory Coast', 'DEF', 2),
  ('O. Diomande', 'Ivory Coast', 'DEF', 2),
  ('G. Doué', 'Ivory Coast', 'DEF', 17),
  ('G. Konan', 'Ivory Coast', 'DEF', 3),
  ('O. Kossounou', 'Ivory Coast', 'DEF', 7),
  ('E. Ndicka', 'Ivory Coast', 'DEF', 21),
  ('W. Singo', 'Ivory Coast', 'DEF', 5),
  ('S. Fofana', 'Ivory Coast', 'MEI', 6),
  ('C. Inao OulaÃ¯', 'Ivory Coast', 'MEI', 19),
  ('F. Kessié', 'Ivory Coast', 'MEI', 8),
  ('I. Sangaré', 'Ivory Coast', 'MEI', 18),
  ('J. Seri', 'Ivory Coast', 'MEI', 4),
  ('B. Touré', 'Ivory Coast', 'MEI', 24),
  ('S. Adingra', 'Ivory Coast', 'ATA', 10),
  ('A. Bonny', 'Ivory Coast', 'ATA', 11),
  ('O. Diakité', 'Ivory Coast', 'ATA', 14),
  ('A. Diallo', 'Ivory Coast', 'ATA', 15),
  ('Y. Diomande', 'Ivory Coast', 'ATA', 26),
  ('E. Guessand', 'Ivory Coast', 'ATA', 22),
  ('P. Guiagon', 'Ivory Coast', 'ATA', 14),
  ('N. Pépé', 'Ivory Coast', 'ATA', 19),
  ('E. Wahi', 'Ivory Coast', 'ATA', 7),
  ('J. Anang', 'Ghana', 'GOL', 12),
  ('S. Mohan', 'Ghana', 'GOL', 16),
  ('L. Zigi', 'Ghana', 'GOL', 1),
  ('J. Adjetey', 'Ghana', 'DEF', 4),
  ('E. Annan', 'Ghana', 'DEF', 21),
  ('A. Djiku', 'Ghana', 'DEF', 23),
  ('D. Köhn', 'Ghana', 'DEF', NULL),
  ('D. Luckassen', 'Ghana', 'DEF', 3),
  ('G. Mensah', 'Ghana', 'DEF', 14),
  ('J. Opoku', 'Ghana', 'DEF', 18),
  ('K. Peprah Oppong', 'Ghana', 'DEF', 15),
  ('P. Pfeiffer', 'Ghana', 'DEF', NULL),
  ('M. Senaya', 'Ghana', 'DEF', NULL),
  ('E. Owusu', 'Ghana', 'MEI', 15),
  ('T. Partey', 'Ghana', 'MEI', 5),
  ('K. Sibo', 'Ghana', 'MEI', 8),
  ('I. Sulemana', 'Ghana', 'MEI', 8),
  ('Caleb Marfo Yirenkyi', 'Ghana', 'MEI', 3),
  ('P. Adu', 'Ghana', 'ATA', NULL),
  ('D. Agyei', 'Ghana', 'MEI', 13),
  ('J. Ayew', 'Ghana', 'ATA', 9),
  ('C. Bonsu Baah', 'Ghana', 'ATA', 17),
  ('A. Fatawu', 'Ghana', 'ATA', 7),
  ('R. Königsdörffer', 'Ghana', 'ATA', 18),
  ('A. Semenyo', 'Ghana', 'ATA', NULL),
  ('K. Sulemana', 'Ghana', 'ATA', 22),
  ('M. Epolo', 'DR Congo', 'GOL', 21),
  ('T. Fayulu', 'DR Congo', 'GOL', 16),
  ('L. Mpasi', 'DR Congo', 'GOL', 1),
  ('D. Batubinsika', 'DR Congo', 'DEF', 5),
  ('R. Bushiri', 'DR Congo', 'DEF', 15),
  ('G. Kalulu', 'DR Congo', 'DEF', 24),
  ('S. Kapuadi', 'DR Congo', 'DEF', 3),
  ('J. Kayembe', 'DR Congo', 'DEF', 12),
  ('A. Masuaku', 'DR Congo', 'DEF', 11),
  ('C. Mbemba', 'DR Congo', 'DEF', 22),
  ('A. Tuanzebe', 'DR Congo', 'DEF', 4),
  ('A. Wan-Bissaka', 'DR Congo', 'DEF', 2),
  ('G. Kakuta', 'DR Congo', 'MEI', 11),
  ('E. Kayembe', 'DR Congo', 'MEI', 5),
  ('B. Cipenga', 'DR Congo', 'MEI', 9),
  ('S. Moutoussamy', 'DR Congo', 'MEI', 8),
  ('N. Mukau', 'DR Congo', 'MEI', 6),
  ('C. Pickel', 'DR Congo', 'MEI', 18),
  ('N. Sadiki', 'DR Congo', 'MEI', 14),
  ('C. Bakambu', 'DR Congo', 'ATA', 17),
  ('S. Banza', 'DR Congo', 'ATA', 23),
  ('T. Bongonda', 'DR Congo', 'ATA', 10),
  ('M. Elia', 'DR Congo', 'ATA', 13),
  ('F. Mayele', 'DR Congo', 'ATA', 19),
  ('N. Mbuku', 'DR Congo', 'ATA', 7),
  ('Y. Wissa', 'DR Congo', 'ATA', 20),
  ('S. Chaine', 'South Africa', 'GOL', 16),
  ('R. Goss', 'South Africa', 'GOL', 22),
  ('R. Leaner', 'South Africa', 'GOL', 1),
  ('R. Williams', 'South Africa', 'GOL', 1),
  ('S. Kabini', 'South Africa', 'DEF', 18),
  ('M. Mbokazi', 'South Africa', 'DEF', 14),
  ('A. Modiba', 'South Africa', 'DEF', 6),
  ('K. Mudau', 'South Africa', 'DEF', 20),
  ('K. Ndamase', 'South Africa', 'DEF', 3),
  ('S. Ngezana', 'South Africa', 'DEF', 21),
  ('I. Okon', 'South Africa', 'DEF', 5),
  ('N. Sibisi', 'South Africa', 'DEF', 19),
  ('T. Smith', 'South Africa', 'DEF', 2),
  ('J. Adams', 'South Africa', 'MEI', 8),
  ('B. Aubaas', 'South Africa', 'MEI', 15),
  ('T. Matuludi', 'South Africa', 'MEI', 25),
  ('T. Mbatha', 'South Africa', 'MEI', 5),
  ('S. Mbule', 'South Africa', 'MEI', 17),
  ('T. Mokoena', 'South Africa', 'MEI', 4),
  ('S. Sithole', 'South Africa', 'MEI', 13),
  ('T. Zwane', 'South Africa', 'MEI', 11),
  ('O. Appollis', 'South Africa', 'ATA', 7),
  ('S. Campbell', 'South Africa', 'ATA', 24),
  ('L. Foster', 'South Africa', 'ATA', 9),
  ('B. Hlongwane', 'South Africa', 'ATA', 12),
  ('E. Makgopa', 'South Africa', 'ATA', 23),
  ('T. Maseko', 'South Africa', 'ATA', 12),
  ('R. Mofokeng', 'South Africa', 'ATA', 10),
  ('E. Mokwana', 'South Africa', 'ATA', 12),
  ('T. Moremi', 'South Africa', 'ATA', 8),
  ('M. Nkota', 'South Africa', 'ATA', 11),
  ('Kilian Belazzoug', 'Algeria', 'GOL', NULL),
  ('A. Mandréa', 'Algeria', 'GOL', 1),
  ('M. Mastil', 'Algeria', 'GOL', NULL),
  ('L. Zidane', 'Algeria', 'GOL', 23),
  ('A. Abada', 'Algeria', 'DEF', 19),
  ('R. Aït-Nouri', 'Algeria', 'DEF', 15),
  ('H. Baouche', 'Algeria', 'DEF', 2),
  ('Z. Belaïd', 'Algeria', 'DEF', 5),
  ('R. Belghali', 'Algeria', 'DEF', 25),
  ('R. Benchaa', 'Algeria', 'DEF', 22),
  ('R. Bensebaïni', 'Algeria', 'DEF', 21),
  ('M. Dorval', 'Algeria', 'DEF', 3),
  ('R. Halaïmia', 'Algeria', 'DEF', 12),
  ('A. Mandi', 'Algeria', 'DEF', 2),
  ('S. Nair', 'Algeria', 'DEF', 4),
  ('H. Aouar', 'Algeria', 'MEI', 8),
  ('A. Aouchiche', 'Algeria', 'MEI', 10),
  ('H. Boudaoui', 'Algeria', 'MEI', 14),
  ('I. Maza', 'Algeria', 'MEI', 22),
  ('H. Mrezigue', 'Algeria', 'MEI', 15),
  ('Y. Titraoui', 'Algeria', 'MEI', 8),
  ('R. Zerrouki', 'Algeria', 'MEI', 6),
  ('M. Amoura', 'Algeria', 'ATA', 18),
  ('A. Benbouali', 'Algeria', 'ATA', NULL),
  ('A. Boulbina', 'Algeria', 'ATA', 27),
  ('F. Chaïbi', 'Algeria', 'ATA', 17),
  ('Amin Chiakha', 'Algeria', 'ATA', 9),
  ('F. Ghedjemis', 'Algeria', 'ATA', NULL),
  ('A. Gouiri', 'Algeria', 'ATA', 11),
  ('A. Hadj-Moussa', 'Algeria', 'ATA', 11),
  ('R. Mahrez', 'Algeria', 'ATA', 7),
  ('Márcio Rosa', 'Cape Verde', 'GOL', 12),
  ('Vózinha', 'Cape Verde', 'GOL', 1),
  ('C. dos Santos', 'Cape Verde', 'GOL', 21),
  ('Diney Borges', 'Cape Verde', 'DEF', 3),
  ('Logan Costa', 'Cape Verde', 'DEF', 5),
  ('S. Lopes Cabral', 'Cape Verde', 'DEF', 13),
  ('Pico', 'Cape Verde', 'DEF', 4),
  ('S. Moreira', 'Cape Verde', 'DEF', 22),
  ('Wagner Pina', 'Cape Verde', 'DEF', 7),
  ('Kelvin Pires', 'Cape Verde', 'DEF', 13),
  ('Stopira', 'Cape Verde', 'DEF', 2),
  ('Telmo Arcanjo', 'Cape Verde', 'MEI', 18),
  ('Deroy Duarte', 'Cape Verde', 'MEI', 14),
  ('L. Duarte', 'Cape Verde', 'MEI', 15),
  ('João Paulo', 'Cape Verde', 'MEI', 8),
  ('Kevin Pina', 'Cape Verde', 'MEI', 6),
  ('Jamiro Monteiro', 'Cape Verde', 'MEI', 10),
  ('Yannick Semedo', 'Cape Verde', 'MEI', 16),
  ('Gilson Benchimol', 'Cape Verde', 'ATA', 9),
  ('Nuno da Costa', 'Cape Verde', 'ATA', 21),
  ('Jovane Cabral', 'Cape Verde', 'ATA', 7),
  ('D. Livramento', 'Cape Verde', 'ATA', 9),
  ('Ryan Mendes', 'Cape Verde', 'ATA', 20),
  ('Garry Rodrigues', 'Cape Verde', 'ATA', 11),
  ('Willy Semedo', 'Cape Verde', 'ATA', 17),
  ('Hélio Varela', 'Cape Verde', 'ATA', 19),
  ('Yazid Abu Layla', 'Jordan', 'GOL', 1),
  ('Abdallah Al Fakhouri', 'Jordan', 'GOL', 22),
  ('A. Al Talalga', 'Jordan', 'GOL', 22),
  ('Noureddin Zaid', 'Jordan', 'GOL', 22),
  ('Malek Shalabiya', 'Jordan', 'GOL', 12),
  ('H. Abu Al Dahab', 'Jordan', 'DEF', 4),
  ('Yousef Abu Al Jazar', 'Jordan', 'DEF', 6),
  ('M. Abu Hasheesh', 'Jordan', 'DEF', 2),
  ('M. Abualnadi', 'Jordan', 'DEF', 16),
  ('Yazan Al Arab', 'Jordan', 'DEF', 5),
  ('Hadi Al Hourani', 'Jordan', 'DEF', 5),
  ('Adham Al Quraishi', 'Jordan', 'DEF', 23),
  ('Saed Al Rosan', 'Jordan', 'DEF', 19),
  ('Ahmad Assaf', 'Jordan', 'DEF', 17),
  ('A. A. Asad Hajabi', 'Jordan', 'DEF', 3),
  ('Abdallah Naseeb', 'Jordan', 'DEF', 3),
  ('Saleem Obaid', 'Jordan', 'DEF', 18),
  ('Issam Smeeri', 'Jordan', 'DEF', 17),
  ('M. Abu Dahab', 'Jordan', 'MEI', 4),
  ('Mohannad Abu Taha', 'Jordan', 'MEI', 20),
  ('M. Al Daoud', 'Jordan', 'MEI', 15),
  ('Mahmoud Al Mardi', 'Jordan', 'MEI', 13),
  ('Nizar Al Rashdan', 'Jordan', 'MEI', 21),
  ('Noor Al Rawabdeh', 'Jordan', 'MEI', 8),
  ('Rajaei Ayed', 'Jordan', 'MEI', 14),
  ('Amer Jamous', 'Jordan', 'MEI', 6),
  ('Y. Qashi', 'Jordan', 'MEI', 6),
  ('Ibrahim Sa''deh', 'Jordan', 'MEI', 15),
  ('Mohammed Abu Zurayq', 'Jordan', 'MEI', 7),
  ('O. Al Fakhouri', 'Jordan', 'ATA', 10),
  ('Yazan Al Naimat', 'Jordan', 'ATA', 11),
  ('A. Azaizeh', 'Jordan', 'ATA', 23),
  ('Ahmad Ersan', 'Jordan', 'ATA', 10),
  ('Baha&apos; Faisal', 'Jordan', 'ATA', 9),
  ('Ali Olwan', 'Jordan', 'ATA', 9),
  ('Ibrahim Sabra', 'Jordan', 'ATA', 18),
  ('M. Taha', 'Jordan', 'ATA', 13),
  ('Mousa Tamari', 'Jordan', 'ATA', 10),
  ('Kamil Saad', 'Iraq', 'GOL', 12),
  ('Ahmed Basil', 'Iraq', 'GOL', 22),
  ('Fahad Talib', 'Iraq', 'GOL', 1),
  ('Hussein Ali', 'Iraq', 'DEF', 3),
  ('Merchas Doski', 'Iraq', 'DEF', 23),
  ('Ahmed Hasan Al Reeshawee', 'Iraq', 'DEF', 23),
  ('Frans Putros', 'Iraq', 'DEF', 6),
  ('M. Sadoun', 'Iraq', 'DEF', 21),
  ('Rebin Solaka', 'Iraq', 'DEF', 2),
  ('Zayed Tahseen', 'Iraq', 'DEF', 4),
  ('Munaf Younus', 'Iraq', 'DEF', 6),
  ('Amir Al Ammari', 'Iraq', 'MEI', 16),
  ('Youssef Amyn', 'Iraq', 'MEI', 7),
  ('Ibraheem Bayesh', 'Iraq', 'MEI', 8),
  ('Akam Rahman', 'Iraq', 'MEI', 5),
  ('Zidane Iqbal', 'Iraq', 'MEI', 14),
  ('Z. Ismaeel', 'Iraq', 'MEI', 15),
  ('A. Jasim', 'Iraq', 'MEI', 17),
  ('A. Sher', 'Iraq', 'MEI', 20),
  ('Kevin Yakob', 'Iraq', 'MEI', 19),
  ('H. Abdulkareem', 'Iraq', 'ATA', 11),
  ('Ali Al Hamadi', 'Iraq', 'ATA', 9),
  ('M. Farji', 'Iraq', 'ATA', 21),
  ('A. Y. Hashim', 'Iraq', 'ATA', 13),
  ('Aymen Hussein', 'Iraq', 'ATA', 18),
  ('Meme', 'Iraq', 'ATA', 10),
  ('B. Ergashev', 'Uzbekistan', 'GOL', 16),
  ('A. Ne&apos;matov', 'Uzbekistan', 'GOL', 12),
  ('U. Yusupov', 'Uzbekistan', 'GOL', 1),
  ('M. Abdumajidov', 'Uzbekistan', 'DEF', NULL),
  ('K. Alijonov', 'Uzbekistan', 'DEF', 3),
  ('R. Ashurmatov', 'Uzbekistan', 'DEF', 5),
  ('U. Eshmurodov', 'Uzbekistan', 'DEF', 15),
  ('B. Karimov', 'Uzbekistan', 'DEF', 16),
  ('M. Khamraliev', 'Uzbekistan', 'DEF', 5),
  ('A. Khusanov', 'Uzbekistan', 'DEF', 2),
  ('S. Nasrullayev', 'Uzbekistan', 'DEF', 13),
  ('F. Sayfiev', 'Uzbekistan', 'DEF', 4),
  ('J. Urozov', 'Uzbekistan', 'DEF', 6),
  ('A. Gʻaniyev', 'Uzbekistan', 'MEI', 10),
  ('I. Ibragimov', 'Uzbekistan', 'MEI', 8),
  ('J. Iskanderov', 'Uzbekistan', 'MEI', 8),
  ('O. Hamrobekov', 'Uzbekistan', 'MEI', 9),
  ('A. Mozgovoy', 'Uzbekistan', 'MEI', 6),
  ('U. Rahmonaliyev', 'Uzbekistan', 'MEI', 15),
  ('O. Shukurov', 'Uzbekistan', 'MEI', 7),
  ('S. Temirov', 'Uzbekistan', 'MEI', 11),
  ('D. Khamdamov', 'Uzbekistan', 'ATA', 17),
  ('A. Odilov', 'Uzbekistan', 'ATA', 28),
  ('I. Sergeev', 'Uzbekistan', 'ATA', 21),
  ('E. Shomurodov', 'Uzbekistan', 'ATA', 14),
  ('O. O&apos;runov', 'Uzbekistan', 'ATA', 11),
  ('Mahmud Abunada', 'Qatar', 'GOL', 21),
  ('Meshaal Barsham', 'Qatar', 'GOL', 22),
  ('Shehab Ellethy', 'Qatar', 'GOL', 1),
  ('Homam Ahmed', 'Qatar', 'DEF', 14),
  ('Sultan Al Braik', 'Qatar', 'DEF', 18),
  ('A. Al Hussain', 'Qatar', 'DEF', 4),
  ('A. Al Oui', 'Qatar', 'DEF', 13),
  ('Youssef Ayman', 'Qatar', 'DEF', 15),
  ('Jassem Gaber', 'Qatar', 'DEF', 8),
  ('Lucas Mendes', 'Qatar', 'DEF', 3),
  ('Assim Madibo', 'Qatar', 'DEF', 23),
  ('Mohamed Al Manai', 'Qatar', 'MEI', 17),
  ('Ali', 'Qatar', 'MEI', 12),
  ('Ahmed Fathi', 'Qatar', 'MEI', 20),
  ('Abdulaziz Hatem', 'Qatar', 'MEI', 6),
  ('G. Laye', 'Qatar', 'MEI', 2),
  ('Tarek Salman', 'Qatar', 'MEI', 5),
  ('Mohammed Waad', 'Qatar', 'MEI', 4),
  ('Akram Afif', 'Qatar', 'ATA', 10),
  ('Ahmed Alaa', 'Qatar', 'ATA', 7),
  ('Edmilson Junior', 'Qatar', 'ATA', 11),
  ('M. Gouda', 'Qatar', 'ATA', 11),
  ('Mohammed Muntari', 'Qatar', 'ATA', 9),
  ('R. Fernandez', 'Paraguay', 'GOL', 12),
  ('O. Gill', 'Paraguay', 'GOL', 22),
  ('G. Olveira', 'Paraguay', 'GOL', 1),
  ('O. Alderete', 'Paraguay', 'DEF', 3),
  ('J. Alonso', 'Paraguay', 'DEF', 6),
  ('A. Benítez', 'Paraguay', 'DEF', 13),
  ('J. Cáceres', 'Paraguay', 'DEF', 4),
  ('F. Balbuena', 'Paraguay', 'DEF', 5),
  ('G. Gómez', 'Paraguay', 'DEF', 15),
  ('D. León', 'Paraguay', 'DEF', 4),
  ('A. Maidana', 'Paraguay', 'DEF', 4),
  ('G. Velázquez', 'Paraguay', 'DEF', 2),
  ('D. Bobadilla', 'Paraguay', 'MEI', 16),
  ('J. Canale', 'Paraguay', 'MEI', NULL),
  ('J. Enciso', 'Paraguay', 'MEI', 19),
  ('M. Galarza', 'Paraguay', 'MEI', 23),
  ('D. Gómez', 'Paraguay', 'MEI', 8),
  ('A. Romero', 'Paraguay', 'MEI', 10),
  ('Maurício', 'Paraguay', 'MEI', 20),
  ('B. Ojeda', 'Paraguay', 'MEI', 20),
  ('L. Romero', 'Paraguay', 'MEI', 13),
  ('R. Sosa', 'Paraguay', 'MEI', 7),
  ('M. Almirón', 'Paraguay', 'ATA', 10),
  ('A. Arce', 'Paraguay', 'ATA', 18),
  ('G. Ávalos', 'Paraguay', 'ATA', 19),
  ('G. Caballero', 'Paraguay', 'ATA', 17),
  ('A. Sanabria', 'Paraguay', 'ATA', 9),
  ('D. Cabezas', 'Ecuador', 'GOL', 22),
  ('H. Galíndez', 'Ecuador', 'GOL', 1),
  ('C. Loor', 'Ecuador', 'GOL', 1),
  ('M. Ramírez', 'Ecuador', 'GOL', 12),
  ('G. Valle', 'Ecuador', 'GOL', 22),
  ('P. Estupiñán', 'Ecuador', 'DEF', 7),
  ('P. Hincapié', 'Ecuador', 'DEF', 3),
  ('J. Hurtado', 'Ecuador', 'DEF', 24),
  ('Y. Medina', 'Ecuador', 'DEF', 7),
  ('J. Ordoñez', 'Ecuador', 'DEF', 4),
  ('W. Pacho', 'Ecuador', 'DEF', 6),
  ('J. Porozo', 'Ecuador', 'DEF', 5),
  ('A. Preciado', 'Ecuador', 'DEF', 17),
  ('C. Ramírez', 'Ecuador', 'DEF', 5),
  ('F. Torres', 'Ecuador', 'DEF', 2),
  ('J. Alcívar', 'Ecuador', 'MEI', 18),
  ('M. Caicedo', 'Ecuador', 'MEI', 23),
  ('D. Castillo', 'Ecuador', 'MEI', 16),
  ('A. Franco', 'Ecuador', 'MEI', 21),
  ('P. Mercado', 'Ecuador', 'MEI', 16),
  ('K. Páez', 'Ecuador', 'MEI', 10),
  ('K. Rodríguez', 'Ecuador', 'MEI', 11),
  ('A. Valencia', 'Ecuador', 'MEI', NULL),
  ('P. Vite', 'Ecuador', 'MEI', 15),
  ('J. Yeboah', 'Ecuador', 'MEI', 9),
  ('N. Angulo', 'Ecuador', 'ATA', 20),
  ('J. Caicedo', 'Ecuador', 'ATA', 19),
  ('J. Corozo', 'Ecuador', 'ATA', 18),
  ('Jeremy Arévalo', 'Ecuador', 'ATA', 8),
  ('Elias Legendre Quiñonez', 'Ecuador', 'ATA', 9),
  ('J. Mercado', 'Ecuador', 'ATA', 18),
  ('A. Minda', 'Ecuador', 'ATA', 14),
  ('G. Plata', 'Ecuador', 'ATA', 19),
  ('Bryan Josías Ramírez León', 'Ecuador', 'ATA', 20),
  ('E. Valencia', 'Ecuador', 'ATA', 13),
  ('C. Brady', 'United States', 'GOL', 26),
  ('R. Celentano', 'United States', 'GOL', NULL),
  ('M. Freese', 'United States', 'GOL', 25),
  ('J. Klinsmann', 'United States', 'GOL', 1),
  ('P. Schulte', 'United States', 'GOL', 18),
  ('M. Turner', 'United States', 'GOL', 1),
  ('S. Dest', 'United States', 'DEF', 2),
  ('A. Freeman', 'United States', 'DEF', 16),
  ('M. McKenzie', 'United States', 'DEF', 22),
  ('T. Ream', 'United States', 'DEF', 13),
  ('C. Richards', 'United States', 'DEF', 3),
  ('A. Robinson', 'United States', 'DEF', 5),
  ('M. Robinson', 'United States', 'DEF', 12),
  ('J. Scally', 'United States', 'DEF', 19),
  ('J. Tolkin', 'United States', 'DEF', 2),
  ('A. Trusty', 'United States', 'DEF', 2),
  ('B. Aaronson', 'United States', 'MEI', 11),
  ('S. Berhalter', 'United States', 'MEI', 8),
  ('J. Cardoso', 'United States', 'MEI', 15),
  ('D. Luna', 'United States', 'MEI', 10),
  ('W. McKennie', 'United States', 'MEI', 8),
  ('A. Morris', 'United States', 'MEI', 16),
  ('G. Reyna', 'United States', 'MEI', 7),
  ('C. Roldan', 'United States', 'MEI', 10),
  ('T. Tessmann', 'United States', 'MEI', 11),
  ('M. Tillman', 'United States', 'MEI', 17),
  ('T. Tillman', 'United States', 'MEI', 26),
  ('T. Weah', 'United States', 'MEI', 21),
  ('P. Agyemang', 'United States', 'ATA', 24),
  ('M. Arfsten', 'United States', 'ATA', 18),
  ('F. Balogun', 'United States', 'ATA', 20),
  ('R. Pepi', 'United States', 'ATA', 9),
  ('C. Pulišić', 'United States', 'ATA', 10),
  ('H. Wright', 'United States', 'ATA', 19),
  ('J. Duverger', 'Haiti', 'GOL', 23),
  ('A. Pierre', 'Haiti', 'GOL', 12),
  ('J. Placide', 'Haiti', 'GOL', 1),
  ('Ricardo Ade', 'Haiti', 'DEF', 4),
  ('H. Delcroix', 'Haiti', 'DEF', 5),
  ('J. Duverne', 'Haiti', 'DEF', 22),
  ('M. Expérience', 'Haiti', 'DEF', 8),
  ('D. Lacroix', 'Haiti', 'DEF', 13),
  ('W. Paugain', 'Haiti', 'DEF', 24),
  ('K. Thermoncy', 'Haiti', 'DEF', 3),
  ('J. Bellegarde', 'Haiti', 'MEI', 10),
  ('D. Jean-Jacques', 'Haiti', 'MEI', 17),
  ('L. Pierre', 'Haiti', 'MEI', 14),
  ('W. Pierre', 'Haiti', 'MEI', 6),
  ('C. F. Sainte', 'Haiti', 'MEI', 18),
  ('D. Simon', 'Haiti', 'MEI', NULL),
  ('J. Casimir', 'Haiti', 'ATA', 21),
  ('L. Deedson', 'Haiti', 'ATA', 11),
  ('D. Etienne', 'Haiti', 'ATA', 7),
  ('Y. Fortuné', 'Haiti', 'ATA', 19),
  ('W. Isidor', 'Haiti', 'ATA', 18),
  ('L. Joseph', 'Haiti', 'ATA', NULL),
  ('D. Nazon', 'Haiti', 'ATA', 9),
  ('F. Pierrot', 'Haiti', 'ATA', 20),
  ('R. Providence', 'Haiti', 'ATA', 15),
  ('M. Crocombe', 'New Zealand', 'GOL', 1),
  ('A. Paulsen', 'New Zealand', 'GOL', 12),
  ('M. Woud', 'New Zealand', 'GOL', 1),
  ('Tyler Bindon', 'New Zealand', 'DEF', 4),
  ('M. Boxall', 'New Zealand', 'DEF', 5),
  ('L. Cacace', 'New Zealand', 'DEF', 13),
  ('F. de Vries', 'New Zealand', 'DEF', 21),
  ('C. Elliot', 'New Zealand', 'DEF', 17),
  ('T. Payne', 'New Zealand', 'DEF', 2),
  ('N. Pijnaker', 'New Zealand', 'DEF', 3),
  ('T. Smith', 'New Zealand', 'DEF', 15),
  ('F. Surman', 'New Zealand', 'DEF', 5),
  ('L. Bayliss', 'New Zealand', 'MEI', 17),
  ('J. Bell', 'New Zealand', 'MEI', 6),
  ('M. Garbett', 'New Zealand', 'MEI', 7),
  ('C. McCowatt', 'New Zealand', 'MEI', 20),
  ('A. Rufer', 'New Zealand', 'MEI', 16),
  ('S. Singh', 'New Zealand', 'MEI', 10),
  ('M. Stamenić', 'New Zealand', 'MEI', 8),
  ('R. Thomas', 'New Zealand', 'MEI', 14),
  ('K. Barbarouses', 'New Zealand', 'ATA', 17),
  ('E. Just', 'New Zealand', 'ATA', 11),
  ('B. Old', 'New Zealand', 'ATA', 19),
  ('J. Randall', 'New Zealand', 'ATA', 14),
  ('B. Waine', 'New Zealand', 'ATA', 18),
  ('C. Wood', 'New Zealand', 'ATA', 9),
  ('M. Crépeau', 'Canada', 'GOL', 16),
  ('L. Gavran', 'Canada', 'GOL', NULL),
  ('O. Goodman', 'Canada', 'GOL', 1),
  ('J. Pantemis', 'Canada', 'GOL', 16),
  ('D. St. Clair', 'Canada', 'GOL', 1),
  ('N. Abatneh', 'Canada', 'DEF', 2),
  ('Z. Bassong', 'Canada', 'DEF', 3),
  ('D. Cornelius', 'Canada', 'DEF', 13),
  ('L. De Fougerolles', 'Canada', 'DEF', 15),
  ('R. Laryea', 'Canada', 'DEF', 22),
  ('J. Marshall-Rutty', 'Canada', 'DEF', NULL),
  ('K. Miller', 'Canada', 'DEF', 4),
  ('J. Waterman', 'Canada', 'DEF', 5),
  ('A. Ahmed', 'Canada', 'MEI', 20),
  ('T. Buchanan', 'Canada', 'MEI', 17),
  ('M. Choinière', 'Canada', 'MEI', 6),
  ('S. Eustáquio', 'Canada', 'MEI', 7),
  ('M. Flores', 'Canada', 'MEI', 18),
  ('Malik Henry', 'Canada', 'MEI', NULL),
  ('I. Koné', 'Canada', 'MEI', 8),
  ('J. Osorio', 'Canada', 'MEI', 21),
  ('R. Priso', 'Canada', 'MEI', 8),
  ('N. Saliba', 'Canada', 'MEI', 19),
  ('N. Sigur', 'Canada', 'MEI', 23),
  ('M. de Brienne', 'Canada', 'MEI', NULL),
  ('M. Aiyenero', 'Canada', 'ATA', 9),
  ('T. Bair', 'Canada', 'ATA', 11),
  ('T. Coimbra', 'Canada', 'ATA', 19),
  ('J. David', 'Canada', 'ATA', 10),
  ('P. David', 'Canada', 'ATA', 24),
  ('J. Hoilett', 'Canada', 'ATA', 10),
  ('D. Jebbison', 'Canada', 'ATA', 11),
  ('C. Larin', 'Canada', 'ATA', 9),
  ('L. Millar', 'Canada', 'ATA', 23),
  ('J. Nelson', 'Canada', 'ATA', 25),
  ('T. Oluwaseyi', 'Canada', 'ATA', 12),
  ('A. Pepple', 'Canada', 'ATA', NULL),
  ('J. Russell-Rowe', 'Canada', 'ATA', 12),
  ('J. Shaffelburg', 'Canada', 'ATA', 14),
  ('T. Bodak', 'Curaçao', 'GOL', 22),
  ('T. Doornbusch', 'Curaçao', 'GOL', 23),
  ('E. Room', 'Curaçao', 'GOL', 1),
  ('L. Bacuna', 'Curaçao', 'DEF', 10),
  ('R. Bazoer', 'Curaçao', 'DEF', 24),
  ('J. Brenet', 'Curaçao', 'DEF', 20),
  ('S. Floranus', 'Curaçao', 'DEF', 5),
  ('Deveron Fonville', 'Curaçao', 'DEF', 13),
  ('J. Gaari', 'Curaçao', 'DEF', 3),
  ('A. Martha', 'Curaçao', 'DEF', 15),
  ('T. Noslin', 'Curaçao', 'DEF', 17),
  ('S. Sambo', 'Curaçao', 'DEF', 2),
  ('R. van Eijma', 'Curaçao', 'DEF', 4),
  ('L. Comenencia', 'Curaçao', 'MEI', 8),
  ('K. Felida', 'Curaçao', 'MEI', 21),
  ('B. Kuwas', 'Curaçao', 'MEI', 17),
  ('G. Roemeratoe', 'Curaçao', 'MEI', 6),
  ('J. Antonisse', 'Curaçao', 'ATA', 11),
  ('J. Bacuna', 'Curaçao', 'ATA', 7),
  ('T. Chong', 'Curaçao', 'ATA', 14),
  ('K. Gorré', 'Curaçao', 'ATA', 14),
  ('S. Hansen', 'Curaçao', 'ATA', 12),
  ('G. Kastaneer', 'Curaçao', 'ATA', 9),
  ('J. Locadia', 'Curaçao', 'ATA', 9),
  ('J. Margaritha', 'Curaçao', 'ATA', 16);

-- Verify count
SELECT COUNT(*) as total_players FROM public.players;
SELECT team, COUNT(*) as players FROM public.players GROUP BY team ORDER BY team;
