#!/usr/bin/env node

/**
 * Build script to generate js/config.js from environment variables.
 *
 * Usage:
 *   node scripts/build-config.js
 *
 * Environment variables (from .env or system):
 *   - SUPABASE_URL (required)
 *   - SUPABASE_PUBLISHABLE_KEY (required)
 *
 * The generated config.js is gitignored and should be created
 * during deployment or local development setup.
 */

import { writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

// Load .env file if it exists (for local development)
const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const envPath = join(rootDir, '.env');

if (existsSync(envPath)) {
  const { config } = await import('dotenv');
  config({ path: envPath });
}

// Validate required environment variables
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

const errors = [];
if (!SUPABASE_URL || SUPABASE_URL.includes('YOUR-PROJECT')) {
  errors.push('SUPABASE_URL is required (set in .env or environment)');
}
if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.includes('...')) {
  errors.push('SUPABASE_PUBLISHABLE_KEY is required (set in .env or environment)');
}

if (errors.length > 0) {
  console.error('❌ Configuration errors:');
  errors.forEach(e => console.error(`   - ${e}`));
  console.error('\nCopy .env.example to .env and fill in your Supabase credentials.');
  process.exit(1);
}

// Generate config.js
const configContent = `// SBC 2026 — Frontend config
// Auto-generated by scripts/build-config.js
// DO NOT EDIT MANUALLY - update .env and re-run the build script

export const APP_CONFIG = {
  SUPABASE_URL: '${SUPABASE_URL}',
  SUPABASE_PUBLISHABLE_KEY: '${SUPABASE_PUBLISHABLE_KEY}',
};
`;

const configPath = join(rootDir, 'js', 'config.js');
writeFileSync(configPath, configContent, 'utf8');

console.log('✅ Generated js/config.js');
console.log(`   SUPABASE_URL: ${SUPABASE_URL}`);
console.log(`   SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY.slice(0, 20)}...`);
