-- ============================================================
-- Bolão Copa 2026 — Atribuição dos 3ºs pela TABELA OFICIAL (Annexe C)
-- ============================================================
-- BUG QUE ISTO CORRIGE (descoberto no fim da fase de grupos, 28/jun/2026):
-- a 005_slot_resolution resolvia os slots compostos de 3º (ex.: 3A/B/C/D/F)
-- por BACKTRACKING — achava QUALQUER emparelhamento válido. Mas a FIFA não usa
-- "qualquer matching": a Annexe C do regulamento fixa, para cada uma das 495
-- combinações de 8 grupos qualificados, UMA atribuição oficial. Para a mesma
-- combinação há vários matchings válidos; só um é o oficial. Resultado real:
-- com os 3ºs vindos de A,B,C,D,E,F,J,L, o backtracking trocava Suécia(3F) e
-- Paraguai(3D) entre os jogos de Alemanha(1E) e França(1I).
--
-- FIX: tabela public.third_place_allocation (495 linhas, gerada de
-- scripts/data/gen-thirds-allocation.mjs — mesma fonte de src/js/thirds-
-- allocation.js) + try_assign_thirds passa a CONSULTAR a tabela em vez de
-- fazer backtracking. _backtrack_thirds fica como fallback defensivo.
--
-- Idempotente: no fim chama resolve_match_slots() para RE-RESOLVER o bracket
-- já materializado (a fase de grupos terminou com a atribuição errada gravada).

-- ===== 1) Tabela oficial: combinação de 8 grupos -> atribuição por jogo =====
-- combo: 8 letras de grupo ORDENADAS (ex.: 'ABCDEFJL').
-- assignments: { "1A": "<grupo do 3º que enfrenta 1A>", ... } para os 8 jogos
-- das 32-avos que recebem um 3º (1A,1B,1D,1E,1G,1I,1K,1L).
create table if not exists public.third_place_allocation (
  combo       text primary key,
  assignments jsonb not null
);

truncate public.third_place_allocation;
insert into public.third_place_allocation (combo, assignments) values
  ('ABCDEFGH', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"D","1L":"E"}'::jsonb),
  ('ABCDEFGI', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('ABCDEFGJ', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"E","1L":"J"}'::jsonb),
  ('ABCDEFGK', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('ABCDEFGL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('ABCDEFHI', '{"1A":"H","1B":"E","1D":"B","1E":"C","1G":"A","1I":"F","1K":"D","1L":"I"}'::jsonb),
  ('ABCDEFHJ', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"D","1L":"E"}'::jsonb),
  ('ABCDEFHK', '{"1A":"H","1B":"E","1D":"B","1E":"C","1G":"A","1I":"F","1K":"D","1L":"K"}'::jsonb),
  ('ABCDEFHL', '{"1A":"H","1B":"F","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"E"}'::jsonb),
  ('ABCDEFIJ', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('ABCDEFIK', '{"1A":"C","1B":"E","1D":"B","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABCDEFIL', '{"1A":"C","1B":"E","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABCDEFJK', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('ABCDEFJL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('ABCDEFKL', '{"1A":"C","1B":"E","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCDEGHI', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"E","1L":"I"}'::jsonb),
  ('ABCDEGHJ', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"E","1L":"J"}'::jsonb),
  ('ABCDEGHK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"E","1L":"K"}'::jsonb),
  ('ABCDEGHL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"E"}'::jsonb),
  ('ABCDEGIJ', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"I","1L":"J"}'::jsonb),
  ('ABCDEGIK', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ABCDEGIL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ABCDEGJK', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"J","1L":"K"}'::jsonb),
  ('ABCDEGJL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"J"}'::jsonb),
  ('ABCDEGKL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABCDEHIJ', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"D","1K":"E","1L":"I"}'::jsonb),
  ('ABCDEHIK', '{"1A":"H","1B":"E","1D":"B","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ABCDEHIL', '{"1A":"H","1B":"E","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ABCDEHJK', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"D","1K":"E","1L":"K"}'::jsonb),
  ('ABCDEHJL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"E"}'::jsonb),
  ('ABCDEHKL', '{"1A":"H","1B":"E","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABCDEIJK', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ABCDEIJL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ABCDEIKL', '{"1A":"E","1B":"I","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABCDEJKL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABCDFGHI', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"D","1L":"I"}'::jsonb),
  ('ABCDFGHJ', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"D","1L":"J"}'::jsonb),
  ('ABCDFGHK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"D","1L":"K"}'::jsonb),
  ('ABCDFGHL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"H"}'::jsonb),
  ('ABCDFGIJ', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"I","1L":"J"}'::jsonb),
  ('ABCDFGIK', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABCDFGIL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABCDFGJK', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"J","1L":"K"}'::jsonb),
  ('ABCDFGJL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"J"}'::jsonb),
  ('ABCDFGKL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCDFHIJ', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"D","1L":"I"}'::jsonb),
  ('ABCDFHIK', '{"1A":"H","1B":"F","1D":"B","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ABCDFHIL', '{"1A":"H","1B":"F","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ABCDFHJK', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"D","1L":"K"}'::jsonb),
  ('ABCDFHJL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"H"}'::jsonb),
  ('ABCDFHKL', '{"1A":"H","1B":"F","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABCDFIJK', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABCDFIJL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABCDFIKL', '{"1A":"C","1B":"I","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCDFJKL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCDGHIJ', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"I","1L":"J"}'::jsonb),
  ('ABCDGHIK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ABCDGHIL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ABCDGHJK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"J","1L":"K"}'::jsonb),
  ('ABCDGHJL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"J"}'::jsonb),
  ('ABCDGHKL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABCDGIJK', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('ABCDGIJL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('ABCDGIKL', '{"1A":"I","1B":"G","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABCDGJKL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABCDHIJK', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ABCDHIJL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ABCDHIKL', '{"1A":"H","1B":"I","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABCDHJKL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABCDIJKL', '{"1A":"I","1B":"J","1D":"B","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABCEFGHI', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('ABCEFGHJ', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"E","1L":"J"}'::jsonb),
  ('ABCEFGHK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('ABCEFGHL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('ABCEFGIJ', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"I","1L":"J"}'::jsonb),
  ('ABCEFGIK', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABCEFGIL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABCEFGJK', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"J","1L":"K"}'::jsonb),
  ('ABCEFGJL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"J"}'::jsonb),
  ('ABCEFGKL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCEFHIJ', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('ABCEFHIK', '{"1A":"H","1B":"E","1D":"B","1E":"C","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABCEFHIL', '{"1A":"H","1B":"E","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABCEFHJK', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('ABCEFHJL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('ABCEFHKL', '{"1A":"H","1B":"E","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCEFIJK', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABCEFIJL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABCEFIKL', '{"1A":"E","1B":"I","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCEFJKL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCEGHIJ', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"G","1K":"E","1L":"I"}'::jsonb),
  ('ABCEGHIK', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"H","1K":"I","1L":"K"}'::jsonb),
  ('ABCEGHIL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"H","1K":"L","1L":"I"}'::jsonb),
  ('ABCEGHJK', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"G","1K":"E","1L":"K"}'::jsonb),
  ('ABCEGHJL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"G","1K":"L","1L":"E"}'::jsonb),
  ('ABCEGHKL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABCEGIJK', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('ABCEGIJL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('ABCEGIKL', '{"1A":"E","1B":"G","1D":"B","1E":"A","1G":"I","1I":"C","1K":"L","1L":"K"}'::jsonb),
  ('ABCEGJKL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABCEHIJK', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"H","1K":"I","1L":"K"}'::jsonb),
  ('ABCEHIJL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"H","1K":"L","1L":"I"}'::jsonb),
  ('ABCEHIKL', '{"1A":"E","1B":"I","1D":"B","1E":"C","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABCEHJKL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABCEIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"A","1G":"I","1I":"C","1K":"L","1L":"K"}'::jsonb),
  ('ABCFGHIJ', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"I","1L":"J"}'::jsonb),
  ('ABCFGHIK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABCFGHIL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABCFGHJK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"J","1L":"K"}'::jsonb),
  ('ABCFGHJL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"J"}'::jsonb),
  ('ABCFGHKL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCFGIJK', '{"1A":"C","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('ABCFGIJL', '{"1A":"C","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('ABCFGIKL', '{"1A":"I","1B":"G","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCFGJKL', '{"1A":"C","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABCFHIJK', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABCFHIJL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABCFHIKL', '{"1A":"H","1B":"I","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCFHJKL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCFIJKL', '{"1A":"I","1B":"J","1D":"B","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABCGHIJK', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('ABCGHIJL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('ABCGHIKL', '{"1A":"I","1B":"G","1D":"B","1E":"C","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABCGHJKL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABCGIJKL', '{"1A":"I","1B":"J","1D":"B","1E":"C","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABCHIJKL', '{"1A":"I","1B":"J","1D":"B","1E":"C","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABDEFGHI', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('ABDEFGHJ', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"E","1L":"J"}'::jsonb),
  ('ABDEFGHK', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('ABDEFGHL', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('ABDEFGIJ', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"I","1L":"J"}'::jsonb),
  ('ABDEFGIK', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABDEFGIL', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABDEFGJK', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"J","1L":"K"}'::jsonb),
  ('ABDEFGJL', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"J"}'::jsonb),
  ('ABDEFGKL', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABDEFHIJ', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('ABDEFHIK', '{"1A":"H","1B":"E","1D":"B","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABDEFHIL', '{"1A":"H","1B":"E","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABDEFHJK', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('ABDEFHJL', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('ABDEFHKL', '{"1A":"H","1B":"E","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABDEFIJK', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABDEFIJL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABDEFIKL', '{"1A":"E","1B":"I","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABDEFJKL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABDEGHIJ', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"E","1L":"I"}'::jsonb),
  ('ABDEGHIK', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"A","1I":"H","1K":"I","1L":"K"}'::jsonb),
  ('ABDEGHIL', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"A","1I":"H","1K":"L","1L":"I"}'::jsonb),
  ('ABDEGHJK', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"E","1L":"K"}'::jsonb),
  ('ABDEGHJL', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"L","1L":"E"}'::jsonb),
  ('ABDEGHKL', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABDEGIJK', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('ABDEGIJL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('ABDEGIKL', '{"1A":"E","1B":"G","1D":"B","1E":"A","1G":"I","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABDEGJKL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABDEHIJK', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"A","1I":"H","1K":"I","1L":"K"}'::jsonb),
  ('ABDEHIJL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"A","1I":"H","1K":"L","1L":"I"}'::jsonb),
  ('ABDEHIKL', '{"1A":"E","1B":"I","1D":"B","1E":"D","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABDEHJKL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABDEIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"A","1G":"I","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ABDFGHIJ', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"I","1L":"J"}'::jsonb),
  ('ABDFGHIK', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABDFGHIL', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABDFGHJK', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"J","1L":"K"}'::jsonb),
  ('ABDFGHJL', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"J"}'::jsonb),
  ('ABDFGHKL', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABDFGIJK', '{"1A":"F","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('ABDFGIJL', '{"1A":"F","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('ABDFGIKL', '{"1A":"I","1B":"G","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABDFGJKL', '{"1A":"F","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABDFHIJK', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ABDFHIJL', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ABDFHIKL', '{"1A":"H","1B":"I","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABDFHJKL', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABDFIJKL', '{"1A":"I","1B":"J","1D":"B","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABDGHIJK', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('ABDGHIJL', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('ABDGHIKL', '{"1A":"I","1B":"G","1D":"B","1E":"D","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABDGHJKL', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABDGIJKL', '{"1A":"I","1B":"J","1D":"B","1E":"D","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABDHIJKL', '{"1A":"I","1B":"J","1D":"B","1E":"D","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABEFGHIJ', '{"1A":"H","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"E","1L":"I"}'::jsonb),
  ('ABEFGHIK', '{"1A":"E","1B":"G","1D":"B","1E":"F","1G":"A","1I":"H","1K":"I","1L":"K"}'::jsonb),
  ('ABEFGHIL', '{"1A":"E","1B":"G","1D":"B","1E":"F","1G":"A","1I":"H","1K":"L","1L":"I"}'::jsonb),
  ('ABEFGHJK', '{"1A":"H","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"E","1L":"K"}'::jsonb),
  ('ABEFGHJL', '{"1A":"H","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"L","1L":"E"}'::jsonb),
  ('ABEFGHKL', '{"1A":"E","1B":"G","1D":"B","1E":"F","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABEFGIJK', '{"1A":"E","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('ABEFGIJL', '{"1A":"E","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('ABEFGIKL', '{"1A":"E","1B":"G","1D":"B","1E":"A","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABEFGJKL', '{"1A":"E","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABEFHIJK', '{"1A":"E","1B":"J","1D":"B","1E":"F","1G":"A","1I":"H","1K":"I","1L":"K"}'::jsonb),
  ('ABEFHIJL', '{"1A":"E","1B":"J","1D":"B","1E":"F","1G":"A","1I":"H","1K":"L","1L":"I"}'::jsonb),
  ('ABEFHIKL', '{"1A":"E","1B":"I","1D":"B","1E":"F","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABEFHJKL', '{"1A":"E","1B":"J","1D":"B","1E":"F","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABEFIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"A","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABEGHIJK', '{"1A":"E","1B":"J","1D":"B","1E":"A","1G":"H","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('ABEGHIJL', '{"1A":"E","1B":"J","1D":"B","1E":"A","1G":"H","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('ABEGHIKL', '{"1A":"E","1B":"G","1D":"B","1E":"A","1G":"I","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABEGHJKL', '{"1A":"E","1B":"J","1D":"B","1E":"A","1G":"H","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABEGIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"A","1G":"I","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABEHIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"A","1G":"I","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ABFGHIJK', '{"1A":"H","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('ABFGHIJL', '{"1A":"H","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('ABFGHIKL', '{"1A":"H","1B":"G","1D":"B","1E":"A","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABFGHJKL', '{"1A":"H","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABFGIJKL', '{"1A":"I","1B":"J","1D":"B","1E":"F","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ABFHIJKL', '{"1A":"H","1B":"J","1D":"B","1E":"A","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ABGHIJKL', '{"1A":"H","1B":"J","1D":"B","1E":"A","1G":"I","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ACDEFGHI', '{"1A":"H","1B":"G","1D":"E","1E":"C","1G":"A","1I":"F","1K":"D","1L":"I"}'::jsonb),
  ('ACDEFGHJ', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"D","1L":"E"}'::jsonb),
  ('ACDEFGHK', '{"1A":"H","1B":"G","1D":"E","1E":"C","1G":"A","1I":"F","1K":"D","1L":"K"}'::jsonb),
  ('ACDEFGHL', '{"1A":"H","1B":"G","1D":"F","1E":"C","1G":"A","1I":"D","1K":"L","1L":"E"}'::jsonb),
  ('ACDEFGIJ', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('ACDEFGIK', '{"1A":"C","1B":"G","1D":"E","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ACDEFGIL', '{"1A":"C","1B":"G","1D":"E","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ACDEFGJK', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('ACDEFGJL', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('ACDEFGKL', '{"1A":"C","1B":"G","1D":"E","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACDEFHIJ', '{"1A":"H","1B":"J","1D":"E","1E":"C","1G":"A","1I":"F","1K":"D","1L":"I"}'::jsonb),
  ('ACDEFHIK', '{"1A":"H","1B":"E","1D":"F","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ACDEFHIL', '{"1A":"H","1B":"E","1D":"F","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ACDEFHJK', '{"1A":"H","1B":"J","1D":"E","1E":"C","1G":"A","1I":"F","1K":"D","1L":"K"}'::jsonb),
  ('ACDEFHJL', '{"1A":"H","1B":"J","1D":"F","1E":"C","1G":"A","1I":"D","1K":"L","1L":"E"}'::jsonb),
  ('ACDEFHKL', '{"1A":"H","1B":"E","1D":"F","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDEFIJK', '{"1A":"C","1B":"J","1D":"E","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ACDEFIJL', '{"1A":"C","1B":"J","1D":"E","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ACDEFIKL', '{"1A":"C","1B":"E","1D":"I","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACDEFJKL', '{"1A":"C","1B":"J","1D":"E","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACDEGHIJ', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"D","1K":"E","1L":"I"}'::jsonb),
  ('ACDEGHIK', '{"1A":"H","1B":"G","1D":"E","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ACDEGHIL', '{"1A":"H","1B":"G","1D":"E","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ACDEGHJK', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"D","1K":"E","1L":"K"}'::jsonb),
  ('ACDEGHJL', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"D","1K":"L","1L":"E"}'::jsonb),
  ('ACDEGHKL', '{"1A":"H","1B":"G","1D":"E","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDEGIJK', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ACDEGIJL', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ACDEGIKL', '{"1A":"E","1B":"G","1D":"I","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDEGJKL', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDEHIJK', '{"1A":"H","1B":"J","1D":"E","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ACDEHIJL', '{"1A":"H","1B":"J","1D":"E","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ACDEHIKL', '{"1A":"H","1B":"E","1D":"I","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDEHJKL', '{"1A":"H","1B":"J","1D":"E","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDEIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDFGHIJ', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"D","1L":"I"}'::jsonb),
  ('ACDFGHIK', '{"1A":"H","1B":"G","1D":"F","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ACDFGHIL', '{"1A":"H","1B":"G","1D":"F","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ACDFGHJK', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"D","1L":"K"}'::jsonb),
  ('ACDFGHJL', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"L","1L":"H"}'::jsonb),
  ('ACDFGHKL', '{"1A":"H","1B":"G","1D":"F","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDFGIJK', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ACDFGIJL', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ACDFGIKL', '{"1A":"C","1B":"G","1D":"I","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACDFGJKL', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACDFHIJK', '{"1A":"H","1B":"J","1D":"F","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ACDFHIJL', '{"1A":"H","1B":"J","1D":"F","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ACDFHIKL', '{"1A":"H","1B":"F","1D":"I","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDFHJKL', '{"1A":"H","1B":"J","1D":"F","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDFIJKL', '{"1A":"C","1B":"J","1D":"I","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACDGHIJK', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('ACDGHIJL', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('ACDGHIKL', '{"1A":"H","1B":"G","1D":"I","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDGHJKL', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDGIJKL', '{"1A":"I","1B":"G","1D":"J","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACDHIJKL', '{"1A":"H","1B":"J","1D":"I","1E":"C","1G":"A","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('ACEFGHIJ', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('ACEFGHIK', '{"1A":"H","1B":"G","1D":"E","1E":"C","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ACEFGHIL', '{"1A":"H","1B":"G","1D":"E","1E":"C","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ACEFGHJK', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('ACEFGHJL', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('ACEFGHKL', '{"1A":"H","1B":"G","1D":"E","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACEFGIJK', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ACEFGIJL', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ACEFGIKL', '{"1A":"E","1B":"G","1D":"I","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACEFGJKL', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACEFHIJK', '{"1A":"H","1B":"J","1D":"E","1E":"C","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ACEFHIJL', '{"1A":"H","1B":"J","1D":"E","1E":"C","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ACEFHIKL', '{"1A":"H","1B":"E","1D":"I","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACEFHJKL', '{"1A":"H","1B":"J","1D":"E","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACEFIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACEGHIJK', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"A","1I":"H","1K":"I","1L":"K"}'::jsonb),
  ('ACEGHIJL', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"A","1I":"H","1K":"L","1L":"I"}'::jsonb),
  ('ACEGHIKL', '{"1A":"E","1B":"G","1D":"I","1E":"C","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ACEGHJKL', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ACEGIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"C","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ACEHIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"C","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ACFGHIJK', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ACFGHIJL', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ACFGHIKL', '{"1A":"H","1B":"G","1D":"I","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACFGHJKL', '{"1A":"H","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACFGIJKL', '{"1A":"I","1B":"G","1D":"J","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACFHIJKL', '{"1A":"H","1B":"J","1D":"I","1E":"C","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ACGHIJKL', '{"1A":"H","1B":"J","1D":"I","1E":"C","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ADEFGHIJ', '{"1A":"H","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('ADEFGHIK', '{"1A":"H","1B":"G","1D":"E","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ADEFGHIL', '{"1A":"H","1B":"G","1D":"E","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ADEFGHJK', '{"1A":"H","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('ADEFGHJL', '{"1A":"H","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('ADEFGHKL', '{"1A":"H","1B":"G","1D":"E","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ADEFGIJK', '{"1A":"E","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ADEFGIJL', '{"1A":"E","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ADEFGIKL', '{"1A":"E","1B":"G","1D":"I","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ADEFGJKL', '{"1A":"E","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ADEFHIJK', '{"1A":"H","1B":"J","1D":"E","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ADEFHIJL', '{"1A":"H","1B":"J","1D":"E","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ADEFHIKL', '{"1A":"H","1B":"E","1D":"I","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ADEFHJKL', '{"1A":"H","1B":"J","1D":"E","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ADEFIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ADEGHIJK', '{"1A":"E","1B":"G","1D":"J","1E":"D","1G":"A","1I":"H","1K":"I","1L":"K"}'::jsonb),
  ('ADEGHIJL', '{"1A":"E","1B":"G","1D":"J","1E":"D","1G":"A","1I":"H","1K":"L","1L":"I"}'::jsonb),
  ('ADEGHIKL', '{"1A":"E","1B":"G","1D":"I","1E":"D","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ADEGHJKL', '{"1A":"E","1B":"G","1D":"J","1E":"D","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ADEGIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"D","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('ADEHIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"D","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('ADFGHIJK', '{"1A":"H","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('ADFGHIJL', '{"1A":"H","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('ADFGHIKL', '{"1A":"H","1B":"G","1D":"I","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ADFGHJKL', '{"1A":"H","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ADFGIJKL', '{"1A":"I","1B":"G","1D":"J","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ADFHIJKL', '{"1A":"H","1B":"J","1D":"I","1E":"D","1G":"A","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('ADGHIJKL', '{"1A":"H","1B":"J","1D":"I","1E":"D","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('AEFGHIJK', '{"1A":"E","1B":"G","1D":"J","1E":"F","1G":"A","1I":"H","1K":"I","1L":"K"}'::jsonb),
  ('AEFGHIJL', '{"1A":"E","1B":"G","1D":"J","1E":"F","1G":"A","1I":"H","1K":"L","1L":"I"}'::jsonb),
  ('AEFGHIKL', '{"1A":"E","1B":"G","1D":"I","1E":"F","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('AEFGHJKL', '{"1A":"E","1B":"G","1D":"J","1E":"F","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('AEFGIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"F","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('AEFHIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"F","1G":"A","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('AEGHIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"A","1G":"H","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('AFGHIJKL', '{"1A":"H","1B":"J","1D":"I","1E":"F","1G":"A","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('BCDEFGHI', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"H","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('BCDEFGHJ', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"D","1L":"E"}'::jsonb),
  ('BCDEFGHK', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"H","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('BCDEFGHL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('BCDEFGIJ', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('BCDEFGIK', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"E","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BCDEFGIL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"E","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BCDEFGJK', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('BCDEFGJL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('BCDEFGKL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"E","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCDEFHIJ', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"H","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('BCDEFHIK', '{"1A":"C","1B":"E","1D":"B","1E":"D","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BCDEFHIL', '{"1A":"C","1B":"E","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BCDEFHJK', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"H","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('BCDEFHJL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('BCDEFHKL', '{"1A":"C","1B":"E","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCDEFIJK', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"E","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BCDEFIJL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"E","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BCDEFIKL', '{"1A":"C","1B":"E","1D":"B","1E":"D","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCDEFJKL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"E","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCDEGHIJ', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"D","1K":"E","1L":"I"}'::jsonb),
  ('BCDEGHIK', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"H","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('BCDEGHIL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"H","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('BCDEGHJK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"D","1K":"E","1L":"K"}'::jsonb),
  ('BCDEGHJL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"D","1K":"L","1L":"E"}'::jsonb),
  ('BCDEGHKL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"H","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('BCDEGIJK', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"J","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('BCDEGIJL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"J","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('BCDEGIKL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"I","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('BCDEGJKL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"J","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('BCDEHIJK', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"H","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('BCDEHIJL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"H","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('BCDEHIKL', '{"1A":"E","1B":"I","1D":"B","1E":"C","1G":"H","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('BCDEHJKL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"H","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('BCDEIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"I","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('BCDFGHIJ', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"D","1L":"I"}'::jsonb),
  ('BCDFGHIK', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BCDFGHIL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BCDFGHJK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"D","1L":"K"}'::jsonb),
  ('BCDFGHJL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"J"}'::jsonb),
  ('BCDFGHKL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCDFGIJK', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BCDFGIJL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BCDFGIKL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCDFGJKL', '{"1A":"C","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCDFHIJK', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BCDFHIJL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BCDFHIKL', '{"1A":"C","1B":"I","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCDFHJKL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCDFIJKL', '{"1A":"C","1B":"J","1D":"B","1E":"D","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCDGHIJK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('BCDGHIJL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('BCDGHIKL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"I","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('BCDGHJKL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('BCDGIJKL', '{"1A":"I","1B":"G","1D":"B","1E":"C","1G":"J","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('BCDHIJKL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"I","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('BCEFGHIJ', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('BCEFGHIK', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BCEFGHIL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BCEFGHJK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('BCEFGHJL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('BCEFGHKL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCEFGIJK', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BCEFGIJL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BCEFGIKL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCEFGJKL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCEFHIJK', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BCEFHIJL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BCEFHIKL', '{"1A":"E","1B":"I","1D":"B","1E":"C","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCEFHJKL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCEFIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCEGHIJK', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"H","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('BCEGHIJL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"H","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('BCEGHIKL', '{"1A":"E","1B":"G","1D":"B","1E":"C","1G":"I","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('BCEGHJKL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"H","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('BCEGIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"I","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('BCEHIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"C","1G":"I","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('BCFGHIJK', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BCFGHIJL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BCFGHIKL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCFGHJKL', '{"1A":"H","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCFGIJKL', '{"1A":"I","1B":"G","1D":"B","1E":"C","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCFHIJKL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BCGHIJKL', '{"1A":"H","1B":"J","1D":"B","1E":"C","1G":"I","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('BDEFGHIJ', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('BDEFGHIK', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BDEFGHIL', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BDEFGHJK', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('BDEFGHJL', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('BDEFGHKL', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BDEFGIJK', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BDEFGIJL', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BDEFGIKL', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BDEFGJKL', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BDEFHIJK', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BDEFHIJL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BDEFHIKL', '{"1A":"E","1B":"I","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BDEFHJKL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BDEFIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BDEGHIJK', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"H","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('BDEGHIJL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"H","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('BDEGHIKL', '{"1A":"E","1B":"G","1D":"B","1E":"D","1G":"I","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('BDEGHJKL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"H","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('BDEGIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"I","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('BDEHIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"D","1G":"I","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('BDFGHIJK', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('BDFGHIJL', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('BDFGHIKL', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BDFGHJKL', '{"1A":"H","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BDFGIJKL', '{"1A":"I","1B":"G","1D":"B","1E":"D","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BDFHIJKL', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('BDGHIJKL', '{"1A":"H","1B":"J","1D":"B","1E":"D","1G":"I","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('BEFGHIJK', '{"1A":"E","1B":"J","1D":"B","1E":"F","1G":"H","1I":"G","1K":"I","1L":"K"}'::jsonb),
  ('BEFGHIJL', '{"1A":"E","1B":"J","1D":"B","1E":"F","1G":"H","1I":"G","1K":"L","1L":"I"}'::jsonb),
  ('BEFGHIKL', '{"1A":"E","1B":"G","1D":"B","1E":"F","1G":"I","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('BEFGHJKL', '{"1A":"E","1B":"J","1D":"B","1E":"F","1G":"H","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('BEFGIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"F","1G":"I","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('BEFHIJKL', '{"1A":"E","1B":"J","1D":"B","1E":"F","1G":"I","1I":"H","1K":"L","1L":"K"}'::jsonb),
  ('BEGHIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"B","1G":"H","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('BFGHIJKL', '{"1A":"H","1B":"J","1D":"B","1E":"F","1G":"I","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('CDEFGHIJ', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"H","1I":"F","1K":"E","1L":"I"}'::jsonb),
  ('CDEFGHIK', '{"1A":"C","1B":"G","1D":"E","1E":"D","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('CDEFGHIL', '{"1A":"C","1B":"G","1D":"E","1E":"D","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('CDEFGHJK', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"H","1I":"F","1K":"E","1L":"K"}'::jsonb),
  ('CDEFGHJL', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"H","1I":"F","1K":"L","1L":"E"}'::jsonb),
  ('CDEFGHKL', '{"1A":"C","1B":"G","1D":"E","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CDEFGIJK', '{"1A":"C","1B":"G","1D":"E","1E":"D","1G":"J","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('CDEFGIJL', '{"1A":"C","1B":"G","1D":"E","1E":"D","1G":"J","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('CDEFGIKL', '{"1A":"C","1B":"G","1D":"E","1E":"D","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CDEFGJKL', '{"1A":"C","1B":"G","1D":"E","1E":"D","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CDEFHIJK', '{"1A":"C","1B":"J","1D":"E","1E":"D","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('CDEFHIJL', '{"1A":"C","1B":"J","1D":"E","1E":"D","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('CDEFHIKL', '{"1A":"C","1B":"E","1D":"I","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CDEFHJKL', '{"1A":"C","1B":"J","1D":"E","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CDEFIJKL', '{"1A":"C","1B":"J","1D":"E","1E":"D","1G":"I","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CDEGHIJK', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"H","1I":"D","1K":"I","1L":"K"}'::jsonb),
  ('CDEGHIJL', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"H","1I":"D","1K":"L","1L":"I"}'::jsonb),
  ('CDEGHIKL', '{"1A":"E","1B":"G","1D":"I","1E":"C","1G":"H","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('CDEGHJKL', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"H","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('CDEGIJKL', '{"1A":"E","1B":"G","1D":"I","1E":"C","1G":"J","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('CDEHIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"C","1G":"H","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('CDFGHIJK', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('CDFGHIJL', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('CDFGHIKL', '{"1A":"C","1B":"G","1D":"I","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CDFGHJKL', '{"1A":"C","1B":"G","1D":"J","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CDFGIJKL', '{"1A":"C","1B":"G","1D":"I","1E":"D","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CDFHIJKL', '{"1A":"C","1B":"J","1D":"I","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CDGHIJKL', '{"1A":"H","1B":"G","1D":"I","1E":"C","1G":"J","1I":"D","1K":"L","1L":"K"}'::jsonb),
  ('CEFGHIJK', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('CEFGHIJL', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('CEFGHIKL', '{"1A":"E","1B":"G","1D":"I","1E":"C","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CEFGHJKL', '{"1A":"E","1B":"G","1D":"J","1E":"C","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CEFGIJKL', '{"1A":"E","1B":"G","1D":"I","1E":"C","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CEFHIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"C","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('CEGHIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"C","1G":"H","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('CFGHIJKL', '{"1A":"H","1B":"G","1D":"I","1E":"C","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('DEFGHIJK', '{"1A":"E","1B":"G","1D":"J","1E":"D","1G":"H","1I":"F","1K":"I","1L":"K"}'::jsonb),
  ('DEFGHIJL', '{"1A":"E","1B":"G","1D":"J","1E":"D","1G":"H","1I":"F","1K":"L","1L":"I"}'::jsonb),
  ('DEFGHIKL', '{"1A":"E","1B":"G","1D":"I","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('DEFGHJKL', '{"1A":"E","1B":"G","1D":"J","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('DEFGIJKL', '{"1A":"E","1B":"G","1D":"I","1E":"D","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('DEFHIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"D","1G":"H","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('DEGHIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"D","1G":"H","1I":"G","1K":"L","1L":"K"}'::jsonb),
  ('DFGHIJKL', '{"1A":"H","1B":"G","1D":"I","1E":"D","1G":"J","1I":"F","1K":"L","1L":"K"}'::jsonb),
  ('EFGHIJKL', '{"1A":"E","1B":"J","1D":"I","1E":"F","1G":"H","1I":"G","1K":"L","1L":"K"}'::jsonb);

-- ===== 2) RLS: dado de referência público (somente leitura) =====
alter table public.third_place_allocation enable row level security;
drop policy if exists third_place_allocation_read on public.third_place_allocation;
create policy third_place_allocation_read on public.third_place_allocation
  for select to anon, authenticated using (true);
grant select on public.third_place_allocation to anon, authenticated;

-- ===== 3) try_assign_thirds: CONSULTA a tabela oficial (antes: backtracking) =====
-- Lê _qualified_thirds e _composite_slots (temp tables criadas por
-- resolve_match_slots Step 2). Monta a chave da combinação (8 grupos ordenados),
-- busca a atribuição oficial e aplica. O 1-seed de cada slot composto é o slot
-- do LADO OPOSTO do mesmo jogo (ex.: no jogo do 3A/B/C/D/F o outro lado é 1E).
-- Fallback: se a combinação não estiver na tabela (não deveria ocorrer com 8
-- grupos), cai no _backtrack_thirds antigo para não travar a resolução.
create or replace function public.try_assign_thirds()
returns boolean
language plpgsql
security definer
as $$
declare
  n_slots int;
  v_combo text;
  v_assign jsonb;
  v_slot record;
  v_seed text;
  v_group text;
  v_team text;
  v_solution jsonb;
begin
  select count(*) into n_slots from _composite_slots;
  if n_slots = 0 then return true; end if;

  -- Chave da combinação: letras dos grupos dos 8 melhores 3ºs, ordenadas.
  select string_agg(group_name, '' order by group_name) into v_combo
  from _qualified_thirds;

  select assignments into v_assign
  from public.third_place_allocation where combo = v_combo;

  if v_assign is not null then
    for v_slot in select idx, match_id, side from _composite_slots order by idx loop
      -- 1-seed = slot do lado oposto do mesmo jogo.
      if v_slot.side = 'home' then
        select slot_away into v_seed from public.matches where id = v_slot.match_id;
      else
        select slot_home into v_seed from public.matches where id = v_slot.match_id;
      end if;

      v_group := v_assign ->> v_seed;
      if v_group is null then continue; end if;

      select team into v_team from _qualified_thirds where group_name = v_group;
      if v_team is null then continue; end if;

      if v_slot.side = 'home' then
        update public.matches set team_home = v_team where id = v_slot.match_id;
      else
        update public.matches set team_away = v_team where id = v_slot.match_id;
      end if;
    end loop;
    return true;
  end if;

  -- Fallback defensivo (combinação inesperada): backtracking antigo.
  raise warning '[try_assign_thirds] combo % fora da tabela oficial — usando backtracking', v_combo;
  v_solution := public._backtrack_thirds(1, n_slots, '{}'::jsonb, ARRAY[]::text[]);
  if v_solution is null then
    raise warning '[try_assign_thirds] BACKTRACKING FALHOU — nenhuma atribuição válida';
    return false;
  end if;
  for v_slot in select idx, match_id, side from _composite_slots order by idx loop
    v_team := v_solution ->> v_slot.idx::text;
    if v_team is not null then
      if v_slot.side = 'home' then
        update public.matches set team_home = v_team where id = v_slot.match_id;
      else
        update public.matches set team_away = v_team where id = v_slot.match_id;
      end if;
    end if;
  end loop;
  return true;
end;
$$;

grant execute on function public.try_assign_thirds() to authenticated;

-- ===== 4) Re-resolve o bracket já materializado com a regra correta =====
-- A fase de grupos terminou com a atribuição errada gravada; Step 0 do
-- resolve_match_slots reseta team_home/away para os slots e re-resolve tudo.
select public.resolve_match_slots();
